### ISSUE TITLE
[Question] How do I get the payer id?

### ISSUE THREAD

**Issue by Khailz** [paypal/PayPal-Python-SDK#101]
I'm following the examples and the field to execute the payment needed is `payer_id`. I want to get this for each payment every time since it changes with the user. How do I go about this instead of doing it manually?

**Comment by avidas** [comment]
The payer_id is appended as a parameter to the redirect_url once they approve of the payment.

**Comment by Khailz** [comment]
I know this already but you have to specify it manually I want to get the `return_url` in a print function so I can use it every time since it's different depending on the user.
