### ISSUE TITLE
Create payment with email only ?

### ISSUE THREAD

**Issue by Arti3DPlayer** [paypal/PayPal-Python-SDK#104]
Can i create payment:

 ```payment = paypalrestsdk.Payment({})```

without ```client_id```, ```client_secret``` etc. only set a **receiver_email**. How can i do this ?

**Comment by avidas** [comment]
@Arti3DPlayer what is your use case? The REST API covers the apis on https://developer.paypal.com/docs/api/ , where you need to register and get an application credentials, (client_id/client_secret pair). You can then [set configuration] and then use paypalrestsdk.Payment({}). So client_id/client_secret would be necessary here.

**Comment by avidas** [comment]
Closing this, reopen if you have further questions.
