### ISSUE TITLE
The data directory is not included in the releases on pypi

### ISSUE THREAD

**Issue by cordery** [paypal/PayPal-Python-SDK#105]
The data directory is not included in the releases on pypi, and so neither of the pems are either.

This causes the WebhookEvent class to not function because it cannot find the pem file:

`No such file or directory: '/home/vagrant/venv/local/lib/python2.7/site-packages/paypalrestsdk/data/DigiCertHighAssuranceEVRootCA.crt.pem'
'NoneType' object has no attribute '_store'
`

**Comment by avidas** [comment]
Hey, you are correct that the pypi published version has the data folder unavailable, we will make a new release soon making it available. Thanks for reporting!
