### ISSUE TITLE
WebhookEvent.verify method returns "No such digest method" when directly passing in HTTP_PAYPAL_AUTH_ALGO

### ISSUE THREAD

**Issue by cordery** [paypal/PayPal-Python-SDK#106]
Looking into it it appears that the header HTTP_PAYPAL_AUTH_ALGO is "SHA256withRSA" but OpenSSL.crypto doesn't recognize this as valid.  I noticed that there is a default value for that argument on WebhookEvent.verify which is "sha256" which IS a recognized digest.  However, the verify method should work if passed the actual http header as specified in the paypal docs.

Digging around a bit it appears that "sha256WithRSAEncryption" is equivalent to "SHA256withRSA" and "sha256WithRSAEncryption" IS a recognized value for OpenSSL.crypto.  I know next to nothing about any of this so I suppose that perhaps these three values are all synonyms for each other.  

The WebhookEvent.verify method should correctly convert the "SHA256withRSA" paypal header message into something that python OpenSSL.crypto understands, however as I'm no expert on this I will not submit a pull request and will let more informed minds figure the best way to resolve this.

**Comment by avidas** [comment]
'sha256' would work here for verification, but we should do a better job with handling if the actual http header gets passed through. We will push a fix which will handle the case if the value of HTTP_PAYPAL_AUTH_ALGO is passed in directly.
