### ISSUE TITLE
Keep getting 500s when executing a payment in sandbox.

### ISSUE THREAD

**Issue by brianbs** [paypal/PayPal-Python-SDK#110]
I'm getting the following message `An internal service error has occurred`

with debug_id: `3aabae6f248c`.  Am I doing something wrong or is PayPals sandbox down?

**Comment by avidas** [comment]
@brianbs this could be an issue relating to availability of the sandbox during that period. Are you still seeing this issue?

**Comment by brianbs** [comment]
@avidas no it seemed to go away.  Where is the best place to see a summary of the debug_id for future reference?

**Comment by avidas** [comment]
@brianbs The debug_id is an identifier that PayPal use internally to look up logs from services. That is not exposed outside, so opening a ticket for the debug id with [PayPal Merchant Technical Support](https://www.paypal.com/mts) is the preferred option to help triage issues such as this in the future.
