### ISSUE TITLE
Will SDK store a credit card into Vault while creating a new payment?

### ISSUE THREAD

**Issue by minibear0523** [paypal/PayPal-Python-SDK#111]
When I create a new paypal payment with credit card which is new to use, will sdk automatically store the credit card information into paypal vault? If no and I want to store card info into vault, should it means that I should store card info into vault and then use the credit card id to create a new payment?

**Comment by avidas** [comment]
Sdk does not automatically vault a credit card, and you have the right idea that you can store it into vault and use the id to create a payment.

**Comment by minibear0523** [comment]
I got it. Thank you. But will it update or add a variable to automatically do that?
