### ISSUE TITLE
Live Mode Logging Warning

### ISSUE THREAD

**Issue by dsanders11** [paypal/PayPal-Python-SDK#113]
When using the API in live mode the message 'Not logging full request/response headers and body in live mode for compliance' is constantly logged to the root logger at warning level. This is rather annoying as there's no way to suppress this log message since it is going to the root logger, short of setting the log level as higher than warning for the root logger (undesirable/bad practice).

The [section](https://github.com/paypal/PayPal-Python-SDK/blob/master/paypalrestsdk/api.py#L191) where the message is logged is the only bit in that file which uses `logging.debug` instead of `log.debug`, which would send it to the named logger for that file. Is that intentional, or simply an oversight?

In addition, even if those lines were changed to use `log.debug`, it seems like the message should be at the 'info' log level, not 'warning'? I don't want to disable all warnings for paypalrestsdk but that would be required to suppress the message in the logs.

I've created a pull request if these changes seem acceptable: #112

**Comment by bluk** [comment]
I merged in your PR. Thanks.
