### ISSUE TITLE
Does this or will this meet the 2016 merchant security roadmap

### ISSUE THREAD

**Issue by jphellemons** [paypal/PayPal-Python-SDK#114]
According to paypal-techsupport.com I should file an issue to ask if this nuget will meet all the requirements for the upcoming changes. I was just wondering if updating the nuget (in the near future) would be sufficient for me.

https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1913&pmv=print&impressions=false&viewlocale=en_US

**Comment by bluk** [comment]
This SDK should meet the 2016 roadmap. The main issue will be if your environment is running an appropriate version of OpenSSL. See the [TLS-update](https://github.com/paypal/TLS-update) and in particular the [Python note](https://github.com/paypal/TLS-update#python) to help determine if your environment is compatible. Hope that helps.
