### ISSUE TITLE
Review your information page in English

### ISSUE THREAD

**Issue by damiann** [paypal/PayPal-Python-SDK#116]
I am using a custom `WebProfile()` with the `locale_code` set to Chinese. The login page loads fine with the Chinese translations, but once I login and then redirected to `Review your information` the page is in English. This page should retain the Chinese translation, no? Is this an issue with PayPal or and I missing something to pass in my configuration?

```
web_profile = WebProfile({
        "name": wpn,
        "presentation": {
            "brand_name": "MySite",
            "logo_image": "https://s3-us-west-1.amazonaws.com/static-bucket-231/img/logo.png",
            "locale_code": "zh_CN"
        },
        "input_fields": {
            "allow_note": False,
            "no_shipping": 1,
            "address_override": 0
        },
        "flow_config": {
            "landing_page_type": "Login",
            "bank_txn_pending_url": review_url
        }
    })

...

payment = Payment({
        "intent": "sale",
        "experience_profile_id": web_profile.id,
        "payer": {
            "payment_method": "paypal"
        },
        "redirect_urls": {
            "return_url": review_url,
            "cancel_url": cart_url
        },
        "transactions": [{
            "item_list": {
                "items": items
            },
            "amount": {
                "currency": "USD",
                "total": str(total)
            },
            "description": ""
        }]
    })
```

**Comment by bluk** [comment]
Your configuration is correct. The `Review Your Information` page is dependent on which country the PayPal Account is created in.

For the Sandbox environment, you can go to https://developer.paypal.com/developer/accounts/ (you may have to login first) and create a test account from the Country you require.

![screen shot 2016-01-27 at 3 26 09 pm](https://cloud.githubusercontent.com/assets/94150/12628783/79ca84bc-c50a-11e5-958c-e7424ac8be6a.png)

Hope that helps. If not, please leave a comment, and sorry for the late response.
