### ISSUE TITLE
Payouts Information

### ISSUE THREAD

**Issue by AlexanderRyzhko** [paypal/PayPal-Python-SDK#123]
Testing in Sandbox:
How can one track payout information?
Once created a payout with Payout class on dashboard there is very limited information about payouts under transaction (only HTTP Status, URL, 	PayPal Debug ID, Transaction Date). Is this only in the Sandbox and in Live on main PayPal Activity it would create an activity under payment send? Or can one get information from payout object retrieved with payout_batch_id, if so where can one find payout amount and email? Can you give more information about payout object and what data and how it is structured there.

**Comment by bluk** [comment]
The PayPal REST API Reference for [Payout API](https://developer.paypal.com/docs/api/#payouts) gives details on what is returned in the response which I think is what you're looking for.

The [Developer Dashboard](https://developer.paypal.com/developer/dashboard/sandbox/) generally gives info about the API calls generically. For other information, you can try to [login to your Sandbox account](https://www.sandbox.paypal.com/home) or use the APIs to get the information you require.
