### ISSUE TITLE
items array is empty on paypalrestsdk.Payment.find

### ISSUE THREAD

**Issue by veroc** [paypal/PayPal-Python-SDK#124]
After creating a payment and paying it through the provided approval_url i'm trying to execute the payment via paypalrestsdk.Payment.find and then execute. The response dict of the find method returns an empty items array so i'm not able to tell what items have been sold.
...
'transactions': [{'amount': {'currency': u'EUR',
                              'details': {'subtotal': u'199.00'},
                              'total': u'199.00'},
                   'description': u'Buchung',
                   'item_list': {'items': [],
                                 'shipping_address': {'city': u'Freiburg',
                                                      'country_code': u'DE',
                                                      'line1': u'ESpachstr. 1',
                                                      'postal_code': u'79111',
                                                      'recipient_name': u'test buyer',
                                                      'state': u'Empty'}},
...

**Comment by bluk** [comment]
Can you share some code on how you created the payment? When I tried the samples to [create a PayPal payment](https://github.com/paypal/PayPal-Python-SDK/blob/master/samples/payment/create_with_paypal.py), approved via the approval URL in my browser, and then called the [execute payment sample](https://github.com/paypal/PayPal-Python-SDK/blob/master/samples/payment/execute.py) (with the payer ID and payment ID replaced with the ones I got from the redirect URL in my browser), I found the items in the find (HTTP GET) response. It should also be in the execute response if you did the raw HTTP request.

```
'item_list': {'items': [{'sku': u'item', 'currency': u'USD', 'price': u'5.00', 'name': u'item', 'quantity': 1}],
```

**Comment by veroc** [comment]
It's pretty much the same code as in the code samples provided with the sdk.
First create payment (api is configured with sandbox credentials):

    # Create payment
    payment = paypalrestsdk.Payment({
        'intent': 'sale',
        'payer': {
            'payment_method': 'paypal',
        },
        'redirect_urls': {
            'return_url': 'XXX'')),
            'cancel_url': 'XXX',
        },
        'transactions': [{
            'item_list': {
                'items': [{
                    'name': 'XXX',
                    'sku': 'ABC123,
                    'price': '199.00',
                    'currency': 'EUR',
                    'quantity': 1,
                }],
            },
            'amount': {
                'total': '199.00',
                'currency': 'EUR',
            },
            'description': 'XXX',
        }],
    })
 
    if payment.create():
        for link in payment.links:
            if link.rel == 'approval_url':
                redirect_url = str(link.href)
                print 'Rediirect to {}'.format(redirect_url)

After PayPal returned to return_url, i'm fetching the data via Payment.find. 

# Lookup payment at return_url
    payment = paypalrestsdk.Payment.find('YYY')

**Comment by veroc** [comment]
i don't know why, but today the result shows the items. sorry.
