### ISSUE TITLE
How to get history based on dates?

### ISSUE THREAD

**Issue by jack1jack** [paypal/PayPal-Python-SDK#127]
Is there a way to provide a date range and get all transactions IDs? 

In the SDK there is the following example:
```
# Fetch Payment
payment = paypalrestsdk.Payment.find("PAY-57363176S1057143SKE2HO3A")

# Get List of Payments
payment_history = paypalrestsdk.Payment.all({"count": 10})
payment_history.payments
```

However,
for find method I need to know the ID
for the all method I need to know how many transactions I have during that period of time.

Basicly I use IPN to get data from paypal but I want to verify that all transactions exists so what I want to do is once a day run a function which will give me all transaction ids, and check if these IDs exists in my DB if not I'll use `find `function to import the data. 

Is there a function in the SDK which can bring data based on dates?

**Comment by juwlee** [comment]
@jack1jack `Payment.all()` can be used to list transactions that match a certain criteria. Please see the code below. The key is `start_time` that you need to pass to the method. You can get the list of parameters from [the developer API docs](https://developer.paypal.com/docs/api/#list-payment-resources).

```
In [2]: %paste
from paypalrestsdk import Payment
import logging
logging.basicConfig(level=logging.INFO)

payment_history = Payment.all({"count": 2, "start_time": "2016-03-06T11:00:00Z"})

# List Payments
print("List Payment:")
for payment in payment_history.payments:
    print("  -> Payment[%s]" % (payment.create_time))

## -- End pasted text --
INFO:paypalrestsdk.api:Request[POST]: https://api.sandbox.paypal.com/v1/oauth2/token
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.sandbox.paypal.com
INFO:paypalrestsdk.api:Response[200]: OK, Duration: 1.699942s.
INFO:paypalrestsdk.api:Request[GET]: https://api.sandbox.paypal.com/v1/payments/payment?count=2&start_time=2016-03-06T11%3A00%3A00Z
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.sandbox.paypal.com
INFO:paypalrestsdk.api:Response[200]: OK, Duration: 4.841950s.
List Payment:
  -> Payment[2016-03-29T14:13:30Z]
  -> Payment[2016-03-29T14:11:22Z]
```
