### ISSUE TITLE
Response message: Unauthorized. 

### ISSUE THREAD

**Issue by test101test101** [paypal/PayPal-Python-SDK#128]
i am trying to connect to paypal but I get an error.

This is my code:
```
import paypalrestsdk
paypalrestsdk.configure({
  "mode": "live", # sandbox or live
  "client_id": "MY KEY",
  "client_secret": "MY SECRET" })

payment_history = paypalrestsdk.Payment.all({"count": 10})
payment_history.payments
for payment in payment_history.payments:
    print("  -> Payment[%s]" % (payment.create_time))
```

I get this error:
`paypalrestsdk.exceptions.UnauthorizedAccess: Failed. Response status: 401. Response message: Unauthorized. Error message: {"error":"invalid_client","error_description":"Client Authentication failed"}`

The keys are correct. What can cause this problem?

**Comment by juwlee** [comment]
Hi @test101test101 is the `mode` set correctly? It seems you are trying to connect to live environment. Are you using your `live` credentials?

**Comment by test101test101** [comment]
Hi juwlee...
Thank you. 

But not I have different error...
`No handlers could be found for logger "paypalrestsdk.api"`

```
    for payment in payment_history.payments:
TypeError: 'NoneType' object is not iterable
```

Why it doesn't work ?

**Comment by bluk** [comment]
@test101test101 Are there payments created in sandbox associated with your app's client ID?

**Comment by test101test101** [comment]
@bluk this is not sandbox, this is live.
