### ISSUE TITLE
Need Webhook Event for Billing Agreement Payment

### ISSUE THREAD

**Issue by ppmtscory** [paypal/PayPal-Python-SDK#132]
New enhancement to track this feature which stems from #69.  An agreement was created and waiting for the payment to test for sure, but thinking that this may be the same underlying reason as #115.  Will use this issue to track and update accordingly.

**Comment by jasonsavard** [comment]
I'd like to help the dev team by pointing out that I do receive recurring payment **emails** from PayPal with the subject line "You received a payment" sent from "service@intl.paypal.com".

Perhaps the developers could refactor this logic to also send out a Webook Event.

**Comment by ppmtscory** [comment]
Thanks @jasonsavard.  IPN can still be used in the meantime as well.  I'm continuing to work with the folks that are responsible for these and will update when I have anything new to share.

**Comment by stewones** [comment]
@ppmtscory  at least here IPN cant be used. for both sandbox or production mode. but works by IPN simulator tool.

**Comment by pp-randy** [comment]
Adding for internal tracking PPPLPAYPT-11612

**Comment by TomMettam** [comment]
I honestly can't believe that this isn't already in place. How is anyone using the billing agreements API without this?  You won't have any idea when the user is paid up to.

**Comment by pp-randy** [comment]
@TomMettam others are using Instant Payment Notification (IPN) in its place.

**Comment by mattLummus** [comment]
@TomMettam documentation for recurring payments with IPN is included [here](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNandPDTVariables/#id08CTB0S055Z). Good luck, definitely more painful than would be to use webhooks.

**Comment by mayconjcm** [comment]
Thanks @mattLummus

**Comment by ppmtscory** [comment]
All - this is now Live.  You will receive a PAYMENT.SALE.COMPLETED webhook for Billing Subscription Payments.

**Comment by grimble67** [comment]
How do I identify the RecurringProfileId, so I can track back to the originating recurring payment record in my system (that was initially returned to me from PayPal when I used PayFlow to set up the recurring payment)? Is it the parent_payment property in the PAYMENT.SALE.COMPLETED payload?

**Comment by ppmtscory** [comment]
The profile ID (I-XXXXXXX) that was returned in the original subscription creation using the Billing Subscription APIs, would be shown as the value of `billing_agreement_id` as displayed below.

`"billing_agreement_id":"I-UKV020XGJMS1"`

**Comment by grimble67** [comment]
@ppmtscory - I'm using RecurringInfo object in PayFlow Pro. When the recurring payment is added (using RecurringAddTransaction), we store the value returned in response.RecurringResponse.ProfileId as the RecurringProfileId. Is this the same thing?

I used the Webhook dashboard to send a test PAYMENT.SALE.COMPLETED message, and the field "billing_agreement_id" wasn't in the payload.

Also, how do I set up my Webhook subscriptions for my Payflow Pro app? When I try to connect my PayPal developer account to my PayFlow Pro account, I get an error saying something like "We're working on bringing this functionality to you soon".

**Comment by ppmtscory** [comment]
Ah... Payflow Pro... my apologies that I missed that before.  I shouldn't assume things.. :)

Payflow Pro does not use REST Applications so there isn't a way for you to get Webhook notifications for those transactions.  For any information on how to get various notifications for the Payflow products, you'll need to reach out to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team.

**Comment by WayneUong** [comment]
@ppmtscory sorry for digging this up. But how can I link the `PAYMENT.SALE.COMPLETED` event to the agreement that generated it. I see a `parent_payment` value, but when I get that payment, there's no reference to the agreement or billing plan either.

Thanks.

**Comment by WayneUong** [comment]
I think the billing-related events are not being sent in sandbox. Maybe these events come from other payments.

**Comment by ppmtscory** [comment]
@WayneUong as stated in a previous comment above, the billing agreement ID would be included in the PAYMENT.SALE.COMPLETED webhook.  These events will only be sent for subscriptions that were set up after this went live which was towards the end of Aug.  If you have brand new subscriptions, where you're not receiving the correct webhooks, or if the webhooks are not being sent in sandbox, then please file a ticket with our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team to have that corrected.

**Comment by mattLummus** [comment]
@ppmtscory 

> "These events will only be sent for subscriptions that were set up after this went live which was towards the end of Aug"

I have not seen this information anywhere else. Where is this documented?

**Comment by mattLummus** [comment]
@ppmtscory Are we expected to cancel our existing subscriptions and have to force our customers to go execute a new one if we want to use the related webhooks?

**Comment by mayconjcm** [comment]
Agreed with @mattLummus.

**Comment by WayneUong** [comment]
@ppmtscory I do receive the billing agreement ID now for recurring payments. But no events were sent on the payment that executes immediately after the agreement. Is there a default trial period that only executes payments on the next cycle after agreement?

Also, billing created events were not sent/created in sandbox either.

**Comment by ppmtscory** [comment]
I've commented on #163

**Comment by diegocouto** [comment]
@ppmtscory I've created new subscriptions and sent some PAYMENT.SALE.COMPLETED using the Webhooks Simulator, but I didn't receive a `billing_agreement_id`. Is there anything about this on the docs?

Also, is it available on the sandbox environment?

**Comment by eduardhasanaj2** [comment]
But why PAYMENT.SALE.REFUNDED do not have a billin aggrement id?

**Comment by hsharma-lsquared** [comment]
Hi there, Why there is no notification from webhooks if a recurring payment is missed or failed?
