### ISSUE TITLE
Unknown Internal Server Error

### ISSUE THREAD

**Issue by rafaelfragosom** [paypal/PayPal-Python-SDK#135]
### General Information

- Mode (Sandbox/Live): **Sandbox**
- PayPal-Debug-ID(s) (from any logs): **b04bcdbf6b18e**
- Version of Python used: **3.5.0**
- SDK Version: **Paypal REST SDK 1.11.5**

### Issue Description

I'm using this lib with django and after I process the payment and get redirected back to my application, I'm getting this error: 

```paypalrestsdk.exceptions.ServerError: Failed. Response status: 500. Response message: Internal Server Erro│
r. Error message: {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_i$":"a503a23a39c0a"} ```

My method looks like this (using Django 1.9):

```python
	def checkout(cls, cart, instagram_user, payment_id, payer_id):
		import paypalrestsdk
		from django.conf import settings

		paypalrestsdk.configure({"mode": settings.PAYPAL_MODE, "client_id": settings.CLIENT_ID, "client_secret": settings.CLIENT_SECRET})
		payment = paypalrestsdk.Payment.find(payment_id)

		payment.execute({"payer_id": payer_id})

		order_id = payment['transactions'][0]['related_resources'][0]['order']['id']
		order = paypalrestsdk.Order.find(order_id)
		order.authorize({"amount": {"currency": settings.PAYPAL_CURRENCY, "total": str(cart.total)}})

		payment_obj = Payment.objects.create(instagram_user=instagram_user, cart=cart, payment_id=payment_id, order_id=order_id, authorization_id=order['id'], buyer_id=payer_id)

		return payment_obj, order
```

I already checked for the credentials, and I'm using all the right ones. I really don't know what's going on.

**Comment by rafaelfragosom** [comment]
Anyone?

**Comment by pp-randy** [comment]
https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/
Brazilian real (BRL) This currency is supported as a payment currency and a currency balance for in-country PayPal accounts only.

@rafaelfragosom I will follow up on the error further if my findings are correct a 500 is not helpful. However, at this time the issue appears to be related to using BRL currency and your buyer account being USA based. Both merchant and buyer need to be Brazil based and the buyer needs a BRL balance.

**Comment by rafaelfragosom** [comment]
That was really helpful. I'm gonna test with Brazilian accounts and get back to you.
Thanks!

**Comment by rafaelfragosom** [comment]
@pp-randy Just tested using a BRL account and charging BRL (Reais). I got the same error.

**Comment by pp-randy** [comment]
At least we ruled out one possible cause. Can you give debug_id?

**Comment by rafaelfragosom** [comment]
Here's the debug id: f8122ade1f0c5

**Comment by rafaelfragosom** [comment]
Anything?

**Comment by pp-randy** [comment]
@rafaelfragosom I apologize I was not able to focus on this and need to run some tests to see if I can reproduce.  As this doesn't appear to be an SDK issue. You might be able to get this resolved sooner working directly with PayPal Technical Support.  You can contact them here: https://www.paypal-techsupport.com/app/ask/.

**Comment by pp-randy** [comment]
@rafaelfragosom So a PayPal payment with BRL accounts and currency is working for me in the sandbox. Can you provide your Create Payment and Execute Payment request strings?  A 500 unfortunately is a catch all many times and hard to see the exact issue.

**Comment by rafaelfragosom** [comment]
@pp-randy  I'm gonna take a closer look at my code, since the problem is not on your end. If I can't figure this out, I'll send you the string. But if I can, I'll post the problem here, for documentation.

**Comment by pp-randy** [comment]
I would appreciate what you can get me, because if it is a coding error we need a more helpful message than 500.

**Comment by pp-randy** [comment]
Can you test your accounts here? https://devtools-paypal.com/guide/pay_paypal/python?interactive=ON&env=sandbox  

Use the API Credentials in the Top Right to plug in your sandbox REST App Credentials.

**Comment by rafaelfragosom** [comment]
It started working back again, for no reason. I guess it was something from your end, I haven't touched the code since. 

Thanks for your help!
