### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Bobspadger** [paypal/PayPal-Python-SDK#136]
### General Information

- Mode (Sandbox/Live): Both
- PayPal-Debug-ID(s) (from any logs):
- Version of Python used: Python 3.4.4
- SDK Version: paypalrestsdk==1.11.5

### Issue Description

> Attempting to just do a simple connect to either Sandbox or Live and I get the following error
```
requests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)
```

Any idea where this issue is cropping up ?

**Comment by netman92** [comment]
+1

**Comment by Bobspadger** [comment]
I think it has to be something to do with the crypto libraries on OS X (other sources round the web seem to confirm this)
Installed on Ubuntu 15.10 and all working ok.

**Comment by pp-randy** [comment]
This is related to TLS changes, more here: https://github.com/paypal/tls-update

@Bobspadger appears Python uses the system supplied OpenSSL, so its possible if you update it then your OS X integration should start working again. https://github.com/paypal/tls-update#python

**Comment by Bobspadger** [comment]
Looks like openssl version `1.0.1c` and on OSX El capitan I have `0.9.8zh`

Not sure on the best course of action for installing or upgrading - will it b0rked OSX?

**Comment by bluk** [comment]
@Bobspadger You can look into using [HomeBrew](http://brew.sh) or [MacPorts](https://www.macports.org) to install a version of OpenSSL and Python that could work. I think most developers do this instead of replacing OS X's version of Python. Just a disclaimer, but YMMV and it's at your own risk, but there have been many developers that do this to install Python, Ruby, etc.

**Comment by Bobspadger** [comment]
For anyone else who hits this issue i've got it working as follows:

```
brew install openssl
brew install python3

brew link python3 --overwrite.
```

I've then had to re-install my packages etc but hey ho - I suppose thats what requirements.txt is for :)

**Comment by Bobspadger** [comment]
Also - for those looking to test their openssl version to check if its `>=1.0.1c`

Terminal:
```
openssl
OpenSSL> version
OpenSSL 1.0.2h  3 May 2016
OpenSSL>
``` 

python:
```
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 19 2015, 20:38:52) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 0.9.8zh 14 Jan 2016'
```
