### ISSUE TITLE
Payment resource does not allow replacements

### ISSUE THREAD

**Issue by maxdore** [paypal/PayPal-Python-SDK#139]
For PP-Plus, we need to do a patch-request towards the API for legal reasons. 

As far as I understood the only change neccessary is that Payment inherits from Replace. If so, I can create a PR.

**Comment by Mdshafiqul** [comment]
![df3f5aeb0cccabb](https://cloud.githubusercontent.com/assets/9559572/16321892/6ba8ed2a-39c1-11e6-971c-e1b3511e1a42.jpg)

**Comment by Mdshafiqul** [comment]
shafiq.bd76@gmail.com

**Comment by ppmtscory** [comment]
Can you outline what you are trying to do and the error that you get?  The options for PATCH are [here](https://developer.paypal.com/docs/api/payments/#payment_update) and must be done prior to the execute call.

**Comment by maxdore** [comment]
We want to do a PATCH-call for a payment resource prior to the execution. Consider the following code:
```python
resource = paypalrestsdk.Payment(data)
operations = [ {
     'op': 'add',
     'path': '/transactions/0/invoice_number', 
     'value': 12345
} ]
resource.replace(operations)
```

This leads to the error `TypeError: 'NoneType' object is not callable` - which is not surprising, because [Payment does not inherit from Replace](https://github.com/paypal/PayPal-Python-SDK/blob/master/paypalrestsdk/payments.py#L7). 

In contrast, [BillingPlan for example does inherit from Replace](https://github.com/paypal/PayPal-Python-SDK/blob/master/paypalrestsdk/payments.py#L27). Therefore, a resource.replace call would work here and lead to a PATCH-request.

The solution is simple as far as I can see: Payment needs to inherit from Replace. PATCH-Requests are available with a replace-call.

**Comment by ppmtscory** [comment]
Thank you for the clarification.  Just doing a simply curl call worked for me so this clarification now makes perfect sense.  I will take a look at what needs to be done and get back to you here.

**Comment by maxdore** [comment]
Thanks. For everyone facing the same Problem, this is a workaround while this issue is not fixed:

```python
from paypalrestsdk.resource import List, Find, Create, Post, Replace

class PatchablePayment(List, Find, Create, Post, Replace):
    """
    The Paypal-SDK does not provide replace operations 
    for payment resources. These are neccessary for the 
    patch-call. Thus, we implement our own payment resource.
    See https://github.com/paypal/PayPal-Python-SDK/issues/139
    for updates and a possible resolution for this workaround
    """
    path = "v1/payments/payment"
    def execute(self, attributes):
        return self.post('execute', attributes, self)
```

Just use this class instead of the normal Payment-Class, e.g. like this:
```python
resource = PatchablePayment.find(paypal_id)
resource.replace(operations)
```
