### ISSUE TITLE
When unable to get token_hash data, raises KeyError

### ISSUE THREAD

**Issue by elithompson** [paypal/PayPal-Python-SDK#142]
### General Information
- Mode (Sandbox/Live): Live
- PayPal-Debug-ID(s) (from any logs): None
- Version of Python used: 2.7.3
- SDK Version: 1.11.5
### Issue Description

On 2016-06-28, I spotted this traceback in my exception logs:

`KeyError: 'token_type`

``` text
File "paypalrestsdk/payments.py", line 224, in create
    return super(Payout, self).create(**kwargs)
  File "paypalrestsdk/resource.py", line 163, in create
    new_attributes = self.api.post(self.path, self.to_dict(), headers, refresh_token)
  File "paypalrestsdk/api.py", line 272, in post
    return self.request(util.join_url(self.endpoint, action), 'POST', body=params or {}, headers=headers or {}, refresh_token=refresh_token)
  File "paypalrestsdk/api.py", line 155, in request
    self.headers(refresh_token=refresh_token), headers or {})
  File "paypalrestsdk/api.py", line 247, in headers
    "Authorization": ("%s %s" % (token_hash['token_type'], token_hash['access_token'])),
```

From Sentry: 
![image](https://cloud.githubusercontent.com/assets/396997/16602195/00630ad2-42c7-11e6-9617-511ee128f5ad.png)

It appears that the [`get_token_hash`](https://github.com/paypal/PayPal-Python-SDK/blob/master/paypalrestsdk/api.py#L70) method is returning a response (`token_hash`) which is just an empty dictionary and causing the `'token_type'` lookup to fail.

My guess is that some anomaly caused this, but the `headers` method should handle this situation a little better. I'd expect that if it didn't have the values it required that it would raise some appropriate exception.

For my use case, I just need to retry the payout operation, but I don't want to try/except on all `KeyError`s. Something like `AccessTokenMissing` or something similar would be great.

**Comment by jaypatel512** [comment]
Hey @elithompson !

Are you able to reproduce this error consistently ? You are absolutely right. We should be passing `AccessTokenMissing` exception or similar on it.

**Comment by elithompson** [comment]
My exception logging shows me that it happened 10 times on 6/28, but not since. IIRC, there was some issue with PayPal on that day.

I'd still love to be able to catch an `AccessTokenMissing` exception so that my automated retry logic would work when this happens in the future.

**Comment by sucithrashanu** [comment]
@elithompson 
Latest SDK version solves your Exception.

Thanks
