### ISSUE TITLE
Payment created with `intent` set to "authorize" does not return an authorization ID 

### ISSUE THREAD

**Issue by zenweasel** [paypal/PayPal-Python-SDK#143]
### General Information

- Mode (Sandbox/Live):
Sandbx
- PayPal-Debug-ID(s) (from any logs):
- Version of Python used:
3.5.2
- SDK Version:
v1.11.6

### Issue Description
I am trying to create a payment for later capture. According to the docs [here](https://developer.paypal.com/docs/integration/direct/capture-payment/#authorize-the-payment) if I set the `intent` to "authorize" I should get back an "authorization" object which contains an ID that I can then use to capture the payment. However I do not receive any "authorization" object, therefore the payment can never be captured.

Below is the test case code I am using. The `payment_object` payload is taken from the documentation.

``` python
import paypalrestsdk
import logging

paypalrestsdk.configure({
  "mode": "sandbox", # sandbox or live
  "client_id": "<client_id>",
  "client_secret": "<client_secret>"})

payment_object = {
    "intent":"authorize",
    "payer":{
      "payment_method":"credit_card",
      "funding_instruments":[
        {
          "credit_card":{
            "number":"5493022963692972",
            "type":"mastercard",
            "expire_month":12,
            "expire_year":2018,
            "cvv2":874,
            "first_name":"Betsy",
            "last_name":"Buyer",
            "billing_address":{
              "line1":"111 First Street",
              "city":"Saratoga",
              "state":"CA",
              "postal_code":"95070",
              "country_code":"US"
            }
          }
        }
      ]
    },
    "transactions":[
      {
        "amount":{
          "total":"7.47",
          "currency":"USD",
          "details":{
            "subtotal":"7.41",
            "tax":"0.03",
            "shipping":"0.03"
          }
        }
      }
    ]
};

payment = paypalrestsdk.Payment(payment_object)

# Create Payment and return status( True or False )
if payment.create():
    print("Payment[%s] created successfully" % (payment.id))
    print(payment)
    assert(payment.transactions[0].related_resources)
else:
    # Display Error message
    print("Error while creating payment:")
    print(payment.error)
```

Note that this seems to be the same bug that is appearing here: https://github.com/paypal/PayPal-node-SDK/issues/168

**Comment by ppmtscory** [comment]
As noted in your issue for the Node SDK, this is being looked into and we'll let you know what we find.  We are aware that this is affecting multiple SDKs.

**Comment by zenweasel** [comment]
Okay, just trying to make it easier to track if these were separate teams.

**Comment by jaypatel512** [comment]
Closing this issue as this is not related to SDK, but with API. Copy of https://github.com/paypal/PayPal-node-SDK/issues/168
