### ISSUE TITLE
CreateInvoice do not work.

### ISSUE THREAD

**Issue by imgrey** [paypal/PayPal-Python-SDK#146]
### General Information

- Mode: Sandbox
- PayPal-Debug-ID(s) (from any logs): 
- Version of Python used: 2.7.10
- SDK Version: Commit 935535acf860c4e13d47a469b2087008c32c2ee1

### Issue Description

I've tried to create the following Invoice.

{'items': [{'name': u'VPS #115 ( 14/06/2016 - 14/07/2016 )', 'unit_price': {'currency': 'USD', 'value': 15}, 'quantity': 1}, {'name': u'Transaction Fee', 'unit_price': 2, 'quantity': 1}], 'merchant_info': {'business_name': 'Me', 'first_name': 'Me', 'last_name': 'Me', 'email': 'sales-facilitator@xentime.com'}, 'billing_info': [{'email': 'test3@mememe.me'}]}

invoice.create() prints the following and returns False:

*** ServerError: Failed. Response status: 500. Response message: Internal Server         Error. Error message:

**Comment by pp-randy** [comment]
At first glance this appears to be a JSON issue {'name'**: u'**VPS
The u before the single quote will cause this JSON not to parse.

**Comment by imgrey** [comment]
u"" is unicode object in Python. I've tried to convert all unicode to str, but error is still the same.

**Comment by imgrey** [comment]
ServerError                               Traceback (most recent call last)
/home/me/.virtualenvs/me/local/lib/python2.7/site-packages/django/core/management/commands/shell.pyc in <module>()
----> 1 create_paypal_invoice('test3@me.com', v)

/home/me/src/me_dev/inventory/tasks.py in create_paypal_invoice(to_email, item)
   1086         pdb.set_trace()
   1087
-> 1088         is_success = invoice.create()
   1089     except Exception as exc:
   1090         raise

/home/me/.virtualenvs/me/local/lib/python2.7/site-packages/paypalrestsdk/resource.pyc in create(self, refresh_token, correlation_id)
    161             headers = self.http_headers()
    162
--> 163         new_attributes = self.api.post(self.path, self.to_dict(), headers, refresh_token)
    164         self.error = None
    165         self.merge(new_attributes)

/home/me/.virtualenvs/me/local/lib/python2.7/site-packages/paypalrestsdk/api.pyc in post(self, action, params, headers, refresh_token)
    270
    271         """
--> 272         return self.request(util.join_url(self.endpoint, action), 'POST', body=params or {}, headers=headers or {}, refresh_token=refresh_token)
    273
    274     def put(self, action, params=None, headers=None, refresh_token=None):

/home/me/.virtualenvs/me/local/lib/python2.7/site-packages/paypalrestsdk/api.pyc in request(self, url, method, body, headers, refresh_token)
    162
    163         try:
--> 164             return self.http_call(url, method, data=json.dumps(body), headers=http_headers)
    165
    166         # Format Error message for bad request

/home/me/.virtualenvs/me/local/lib/python2.7/site-packages/paypalrestsdk/api.pyc in http_call(self, url, method, **kwargs)
    205                 str(response.headers), str(response.content)))
    206
--> 207         return self.handle_response(response, response.content.decode('utf-8'))
    208
    209     def handle_response(self, response, content):

/home/me/.virtualenvs/me/local/lib/python2.7/site-packages/paypalrestsdk/api.pyc in handle_response(self, response, content)
    234             raise exceptions.ClientError(response, content)
    235         elif 500 <= status <= 599:
--> 236             raise exceptions.ServerError(response, content)
    237         else:
    238             raise exceptions.ConnectionError(

ServerError: Failed. Response status: 500. Response message: Internal Server Error. Error message:

**Comment by pp-randy** [comment]
Update 'unit_price': 2,
to 'unit_price': {'currency': 'USD', 'value': 2}

**Comment by imgrey** [comment]
It helped. Thank you.

**Comment by imgrey** [comment]
But I think server exception could have contained at least some "ValueError".

**Comment by pp-randy** [comment]
I agree and will follow up further

**Comment by pp-randy** [comment]
For internal tracking: PPPLPAYPT-11403

**Comment by pp-randy** [comment]
Closing this issue, please let me know if you need further assistance
