### ISSUE TITLE
INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by wasabigeek** [paypal/PayPal-Python-SDK#147]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): 33a4dbd541569, d1c8f26aaeb5f, 651a75f2383b1, 1d571b6c10986, cbda0e50b7ee9
- Version of Python used: 2.7.6
- SDK Version: paypalrestsdk==1.11.7

### Issue Description
ServerError at /api/execute-payment
Failed. Response status: 500. Response message: Internal Server Error. Error message: Failed. Response status: 500. Response message: Internal Server Error. Error message: {"name":"INTERNAL_SERVICE_ERROR","details":[],"message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"cbda0e50b7ee9"}

Using Django, getting a few different errors when I try a few different code iterations. Latest (Which I'd like to add was working perfectly before):

```
class ExecutePaymentView(APIView):
    def post(self, request, format=None):
        configure_paypal()
        payment_id = request.data['payment_id']
        payment = paypalrestsdk.Payment.find(payment_id)

        response = {"state": "failed"}
        if payment.execute({"payer_id": request.data['payer_id']}):
            response['state'] = 'success'
            Order.objects.filter(payment_id=payment_id).update(
                sale_id=payment.transactions[0].related_resources[0].sale.id
            )
        else:
            response['error'] = payment.error

        return Response(response)
```

**Comment by sankarbhavanib** [comment]
Thank you for reporting the issue. we are using [#623] (https://github.com/paypal/PayPal-PHP-SDK/issues/623) to track this issue. 

If you require specific support, please open a ticket with [Merchant Technical Support](https://www.paypal-techsupport.com) who can directly communicate with you.
