### ISSUE TITLE
Can't get Billing Agreement ID

### ISSUE THREAD

**Issue by wasabigeek** [paypal/PayPal-Python-SDK#148]
### General Information
- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): N/A
- Version of Python used: 2.7.6
- SDK Version: 1.11.7
### Issue Description

In the [API documentation](https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_create_response), when a Billing Agreement is created, it's ID is supposed to be returned in the response. I can't seem to get this when I do:

```
if billing_agreement.create():
            ...
            id = billing_agreement.id
            ...
```

Is that expected? I am able to get the Billing Plan ID using `billing_agreement.plan.id`, but as far as I can tell I can't get the Billing Agreement ID from that.

**Comment by sankarbhavanib** [comment]
@wasabigeek  Thank you for pointing out the mistake in documentation. I have created an internal ticket DEVDOC-476 to track this issue.

To clarify your question, at present, the billing agreement object will not return billing agreement id 
you need to complete the execute agreement to get the billing agreement id.

**Comment by wasabigeek** [comment]
@sankarbhavanib is the Billing Plan ID returned during the execution then, so I can use that to record which created billing agreements were executed? The [documentation ](https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_execute) is not too clear on this too - it says the "plan" object is returned, but in the sample response, it's not shown.

**Comment by sankarbhavanib** [comment]
@wasabigeek Again it seems to be a mistake in documentation. I have created an internal ticket DEVDOC-478 to track this issue.

To clarify your question, at present, execute agreement is not returning plan.id number .  you need to use `billing_agreement_create_response.plan.id` for plan id and `billing_agreement_execute_response.id`  to get the agreement id

**Comment by wasabigeek** [comment]
Hi @sankarbhavanib yes, I can get those separately, but is there a way to link the two? I won't know which Billing Plan ID links to which Billing Agreement ID since there isn't anything passed in the query parameters for the execute step, except the token.

**Comment by sankarbhavanib** [comment]
@wasabigeek  I agree with you  both objects should return both values.  I will make sure to send that feedback along with above ticket to API developers

**Comment by AlexzAK** [comment]
Im affected by this too
Please resolve it

**Comment by pianostringquartet** [comment]
Any updates? This could be a really great feature that would make the API much easier to use.

**Comment by egnartsms** [comment]
Affects me, too.

**Comment by pp-randy** [comment]
The request is being tracked here: https://github.com/paypal/PayPal-REST-API-issues/issues/19

Tracking with the url token in the redirect seems to be one way to match the two API calls, more on that here: https://github.com/paypal/PayPal-node-SDK/issues/215#issuecomment-283482767
