### ISSUE TITLE
WebhookEvent.verify() returns [('rsa routines', 'INT_RSA_VERIFY', 'bad signature')]

### ISSUE THREAD

**Issue by yacobell** [paypal/PayPal-Python-SDK#157]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): None
- Version of Python used: 2.7
- SDK Version: 1.11.7

### Issue Description

I'm sending WebhookEvents to my local development environment (via ngrok) using PayPal's Webhook Event Simulator. When I try to verify the WebhookEvent, I get a response of: 

`[('rsa routines', 'INT_RSA_VERIFY', 'bad signature')]`

I narrowed it down to `crypto.verify(cert, b64decode(actual_sig), expected_sig.encode('utf-8'), auth_algo)` in `WebhookEvent._verify_signature()`. 

I can't see what I'm doing wrong. Here is the data I'm using, based on the http request from PayPal.

```
transmission_id = '80d8bb40-79f3-11e6-844a-db178b84cf9d'

timestamp = '2016-09-13T20:49:02Z'

webhook_id = 'bc087a02fe241'

actual_sig = 'Pi+TJY3168K/9ns53FshKZxWWNOnDluiPlKAGoEeWf1nyUKg5sltAMQH1eCKXruJPOgppP2h/iG0h9WECIJpwPvwJHfrJHObXoF0a1zyGD0Hd5/1RSXuX2S1dZ1PCBSFRIAbCUy7tW9osLgIyVyKL2dtIkf6QmY+D/LxaHnL00SRe3z6dudOJalo0jNAeZoDZV/vPLQAf0cfV34BWdJnuaiHa1eFqFFR/Pd+iOcCHVH0w3LSFA3HLk7odPugDUzZmVWfsxzKyIIm0rji+UgJP2N2hQpCxwS2nyUXgRirwm6E4rjFkfjkhA0NBbUrOseZzoJWoKhbjeThaJB91oHZig=='

cert_url = 'https://api.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-df8cd2d5'

auth_algo = 'SHA256withRSA'

event_body = '{"id":"WH-6W4482673W002281V-61985753LP2332451","event_version":"1.0","create_time":"2015-05-11T21:45:15Z","resource_type":"sale","event_type":"PAYMENT.SALE.PENDING","summary":"Payment pending for EUR 3.76 EUR","resource":{"id":"11139561TK568332L","create_time":"2015-05-11T21:44:29Z","update_time":"2015-05-11T21:44:29Z","amount":{"total":"3.76","currency":"EUR"},"payment_mode":"INSTANT_TRANSFER","state":"pending","reason_code":"RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION","protection_eligibility":"INELIGIBLE","parent_payment":"PAY-13V79659LS5126423KVISFPI","links":[{"href":"https://api.paypal.com/v1/payments/sale/11139561TK568332L","rel":"self","method":"GET"},{"href":"https://api.paypal.com/v1/payments/sale/11139561TK568332L/refund","rel":"refund","method":"POST"},{"href":"https://api.paypal.com/v1/payments/payment/PAY-13V79659LS5126423KVISFPI","rel":"parent_payment","method":"GET"}]},"links":[{"href":"https://api.paypal.com/v1/notifications/webhooks-events/WH-6W4482673W002281V-61985753LP2332451","rel":"self","method":"GET"},{"href":"https://api.paypal.com/v1/notifications/webhooks-events/WH-6W4482673W002281V-61985753LP2332451/resend","rel":"resend","method":"POST"}]}'
```

Any ideas what's going wrong?

**Comment by sdcoffey** [comment]
Hey @yacobell,

Sorry for the delay - taking a look at this today. Can you verify that this is still an issue you're having?

**Comment by sdcoffey** [comment]
Hey @yacobell 

So, you actually won't be able to verify webhook events sent using the simulator since we don't include the `webhook_id` in the event body. For testing purposes, I'd just recommend ensuring that you at least receive the events via the simulator, and then do a quick, isolated test in live to make sure that the events are verified correctly.

I'm going to close this for now, feel free to reopen it if you're still seeing this issue.
