### ISSUE TITLE
Didn't receive payment with billing plan

### ISSUE THREAD

**Issue by amasty** [paypal/PayPal-Python-SDK#168]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): 
- Version of Python used: 3.5.1
- SDK Version: 1.11.7

### Issue Description

Billing plan
ID: P-3XU60145LM223782F2LHJLQA (27 usd per day)

Agreement
ID: I-E0C4DG2LUYDW

After execute agreement i received 1 payment.
Transaction ID: 7X8115703P150521K

In message from IPN next payment date should be 'next_payment_date' : '03:00:00 Oct 18, 2016 PDT', 
Today 19 oct. I didn't receive any payment. 

Agreement is active. This from agreement object:
```
{
  'state': 'Active',
  ...
  'next_billing_date': '2016-10-18T10:00:00Z',
}
```

PDT time now
1:36:04AM Wednesday, October 19, 2016

**Comment by bluk** [comment]
@amasty If the billing agreement payment has still not been paid, please contact [PayPal Tech Support](https://www.paypal-techsupport.com/app/ask) with the information you provided. The SDK team does not have access to lookup the sandbox agreement.
