### ISSUE TITLE
express checkout url for aggreement redirects to the legacy non-responsive checkout

### ISSUE THREAD

**Issue by WayneUong** [paypal/PayPal-Python-SDK#177]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): 339189c7540a5, 339189c7540a5
- Version of Python used: 2.7
- SDK Version: latest

### Issue Description

Using sample code, I created an approval redirect link:
https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-0TT81510DJ312244S

It should shows the pretty express checkout screen, but instead it redirects to the old ugly one:
https://www.sandbox.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION=p6zYAIG4wldkE4A41uS8J2qsT1Q34XxQ4vIsnDfCZX7jzmujUyznhue7Pn4&dispatch=50a222a57771920b6a3d7b606239e4d529b525e0b7e69bf0224adecfb0124e9b61f737ba21b0819862118003bc2f4b4f47f01ef0a11094f0

Works fine with payments. Only redirects with agreements.

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by pp-randy** [comment]
@WayneUong are you still getting the older flow?

**Comment by WayneUong** [comment]
it works now that I switched to the latest checkout.
