### ISSUE TITLE
Agreement approval_url does not work with checkout.js V4.0.0

### ISSUE THREAD

**Issue by WayneUong** [paypal/PayPal-Python-SDK#178]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs):
- Version of Python used: latest
- SDK Version: latest

### Issue Description

I used sample code to create a plan and agreement. Then use the latest checkout.js to process the token to redirect user to approve it. After the user clicked `Agree & Continue`, the popup just quits and goes `onCancel` callback is fired. `onAuthorize` is never called.

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by ppmtscory** [comment]
My apologies for the delay in the response, but if this is still an issue for you, I'd recommend filing a ticket with our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team to have them take a look at your integration.  This particular issue wouldn't be SDK specific.
