### ISSUE TITLE
Search invoice option doesn't work

### ISSUE THREAD

**Issue by JosephDev** [paypal/PayPal-Python-SDK#185]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs):
- Version of Python used: 3.5.2
- SDK Version: 1.12.0

### Issue Description

Search invoice path is different from [API document](https://developer.paypal.com/docs/api/invoicing/#invoices_search). 
I changed the url on PR #184. It works fine except searching invoice by its status.
I tried searching request with status parameter using curl but it doesn't work either.

**Comment by xiaoleih41** [comment]
Hi, sorry for the delay.  I have done testing. I have passed the value of **status** as **array**. It worked for me.   Please let me know if it works for you.  Thanks,  Xiaolei
```javascript
"status": ["REFUNDED"]
```

**Comment by JosephDev** [comment]
@xiaoleih41 I don't follow you. would you please explain your test process with your test code?

**Comment by xiaoleih41** [comment]
When I pass the status as string, the system threw an error. However when I pass it as an array **"status":["REFUNDED"], ** it worked for me.  I think I might not have understood your issue correctly. Please provide more detail on the error you have received and the debug ID. Thanks, Xiaolei

**Comment by JosephDev** [comment]
@xiaoleih41 I just tested and you right. search invoices by status accepts array.
I think we should put example and raise error for that.
and also official API document, attached, is little bit ambiguous. 
> status enum
>An enumeration of the invoice statuses.
>Allowed values: DRAFT, SENT, PAID, MARKED_AS_PAID, CANCELLED, REFUNDED, PARTIALLY_REFUNDED, MARKED_AS_REFUNDED.

**Comment by xiaoleih41** [comment]
You are right. The error message was not clear and the "enum" data type is a bit confusing too. I am filing tickets on both the error message and the documentation. Thank you for bringing this to our attention. I will update this thread with the ticket numbers for internal tracking. 
Thanks, 
Xiaolei

**Comment by JosephDev** [comment]
I put search example #191

**Comment by xiaoleih41** [comment]
This issue has been tracked at https://github.com/paypal/PayPal-REST-API-issues/issues/49 and https://github.com/paypal/PayPal-REST-API-issues/issues/53.
