### ISSUE TITLE
Check user exists or not based on email / Mobile number/  PayPal ID

### ISSUE THREAD

**Issue by prasadmuley** [paypal/PayPal-Python-SDK#186]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): 
- Version of Python used: 2.7
- SDK Version: 1.12.0

### Issue Description
Hi Team,

   I've to check whether user's PayPal account exists or not before transferring money. User's account can be verified based on email / phone / PayPal ID.  I searched a lot and didn't find any API / Method. Is there any rest API available?

If there is no API available, what is the ideal way to check user exists or not?
 

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by xiaoleih41** [comment]
Thank you for your question. The recommended best practice is to use Login with PayPal API to obtain user's explicit consent for you to access any user account info.  For more detail, please take a look at https://developer.paypal.com/docs/integration/direct/identity/. Thanks, Xiaolei

**Comment by xiaoleih41** [comment]
Please let me know if you have any further questions. Thanks, Xiaolei

**Comment by Kaushik0704** [comment]
same question, how to check paypal business email is registered in paypal or not using api'

Thanks, Kaushik.

**Comment by Kaushik0704** [comment]
@xiaoleih41 

same question, how to check paypal business email is registered in paypal or not using api.

Thanks, Kaushik.

**Comment by xiaoleih41** [comment]
Login with PayPal will be the only recommended way as I stated earlier. `email` is one of the **scope value** that you can request the user to give you access to.  Please check [here](https://developer.paypal.com/docs/integration/direct/identity/attributes/) for detail.
