### ISSUE TITLE
Payment REST API UNKNOWN_ERROR

### ISSUE THREAD

**Issue by omistler** [paypal/PayPal-Python-SDK#188]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): 33e47094207e
- Version of Python used: 3.5.0 
- SDK Version: 1.12.0

### Issue Description

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

Tried the default payment/create_with_credit_card payment example within my application and it return the next error:

Error while creating payment:
{'message': 'An unknown error occurred.', 'information_link': 'https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR', 'name': 'UNKNOWN_ERROR', 'debug_id': '33e47094207e'}

**Comment by xiaoleih41** [comment]
I noticed that you have a French account. Please consider to create a US or UK pro account instead as the direct credit card processing is available to a limited countries only. Please let me know if that solves the issue or not. 
https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/?mark=direct%20credit%20card
Thanks, Xiaolei

**Comment by omistler** [comment]
I'm in australia and developing for an australian web store, is this ok to create a UK or us account to manage it?

**Comment by pp-randy** [comment]
@omistler I apologize for the delay in response and for development time you have invested in implementing the REST SDK.  REST API and Credit Cards is supported for UK Pro, but will work in the US per the link provided by @xiaoleih41.  

Have you looked into Braintree for Credit Card processing?
https://www.braintreepayments.com/products/braintree-direct
https://www.braintreepayments.com/features/credit-cards

**Comment by xiaoleih41** [comment]
I close this issue.

**Comment by xiaoleih41** [comment]
@**omistler** Please let us know if you have further questions.  thanks, Xiaolei
