### ISSUE TITLE
RATE LIMIT REACHED

### ISSUE THREAD

**Issue by campanate** [paypal/PayPal-Python-SDK#194]
When I change sdk to live, he send several requests to paypal payment and return error 429, sandbox works fine. Someone?

    try:
        mode = 'live'
        if mode == 'sandbox':
            paypalrestsdk.configure(sandbox)
        else:
            paypalrestsdk.configure(live)
        validacao = validate_data(data)
        if validacao['status'] == 'error':
            return validacao
        payment = paypalrestsdk.Payment({
            "intent": "sale",
            "payer": {
                "payment_method": "credit_card",
                "funding_instruments": [{
                    "credit_card": {
                        "type": data['flag'],
                        "number": data['number'],
                        "expire_month": data['month'],
                        "expire_year": data['year'],
                        "cvv2": data['cvv'],
                        "first_name": data['first_name'],
                        "last_name": data['last_name']}}]},
            "transactions": [{
                "item_list": {
                    "items": [{
                        "name": "item",
                        "sku": "item",
                        "price": "1.00",
                        "currency": "USD",
                        "quantity": 1}]},
                "amount": {
                    "total": "1.00",
                    "currency": "USD"},
                "description": "Description."}]})

        if payment.create():
            return {'status': "Payment created successfully"}

        return {'status': 'error', 'message': payment.error}
    except Exception as e:
        print(e)
        return {'error': 'Transação não autorizada.', 'message': e.message}

Failed. Response status: 429. Response message: Too Many Requests. Error message: {"name":"RATE_LIMIT_REACHED","debug_id":"########","message":"Too many requests. Blocked due to rate limiting."}

**Comment by pp-randy** [comment]
Please review the [Rate limiting guidelines](https://developer.paypal.com/docs/classic/lifecycle/rate-limiting/).  

Since this issue is not related to the SDK please follow the above and reach out the Merchant Technical Support if needed.
