### ISSUE TITLE
invoice pagination works incorrectly

### ISSUE THREAD

**Issue by JosephDev** [paypal/PayPal-Python-SDK#195]
* SDK/Library version: latest version (current github) 
* Environment: SandBox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: OSX, python 3.5.2

### Issue description
I tried figure out how paginate invoices. while testing, I've got a funny result that invoice IDs are duplicated in results.

if the page_size > total_count than result is fine. no duplication ID
however, if page_size < total_count than IDs are duplicated in results even if I create several request to retrieve all list. 

example results:
total count: 21, page_size: 21, page: 0 => return 21 UNIQUE invoices
total count: 21, page_size: 50, page: 0 => return 21 UNIQUE invoices

**total count: 21, page_size: 10, page: 5 => return 19 UNIQUE invoices
total count: 21, page_size: 10, page: 0,1,2 => return 12 UNIQUE invoices**

Here is my sample search code. 
```
options = {
  "page_size": 30,
  "total_count_required": True,
  "status": ["SENT"],
  "page": 0
}
invoices = paypalrestsdk.Invoice.search(options)
```

**Comment by pp-randy** [comment]
Thank you for the helpful information on reproducing the issue.  This is an API issue so I will follow up further with more details after I get a new issue created in our REST API tracking repo [PayPal-REST-API-issues](https://github.com/paypal/PayPal-REST-API-issues).

**Comment by JosephDev** [comment]
@pp-randy thank for letting me know. Moreover I think PayPal REST API document is also updated with `MAX SIZE` on `page_size`.
I think it has limit (my experiment says it is 100) but no mentions.

[API Reference](https://developer.paypal.com/docs/api/invoicing/#invoices_search)
```
page_size number
The page size for the search results.
```

**Comment by pp-randy** [comment]
I will probably create a separate issue for documentation, so if you see anything else let me know.  

I noticed this as well in the documentation. The default for page is 0 in my testing with [Listing Invoices](https://developer.paypal.com/docs/api/invoicing/#invoices_get-all), but shows as 1.

**Comment by JosephDev** [comment]
@pp-randy okay. I just wonder I can create an issue on the repo because it looks like inside use only. I will create an issue on the repo. in future if I have one.

**Comment by pp-randy** [comment]
For the duplicate invoice API issue I will be tracking here: https://github.com/paypal/PayPal-REST-API-issues/issues/65

**Comment by pp-randy** [comment]
Thank you for the new issue to clarify the documentation.  I have added internal tracking information to it.
