### ISSUE TITLE
WebhookEvent.verify() returns [('rsa routines', 'INT_RSA_VERIFY', 'bad signature')

### ISSUE THREAD

**Issue by dhruvsingh** [paypal/PayPal-Python-SDK#196]
### General information

* SDK/Library version: 1.11.5
* Environment:  Sandbox
* `PayPal-Debug-ID` values:  None
* Language, language version, and OS:  Ubuntu 14.04 LTS, Python 2.7.6

The issues I looked at before posting my problem are:
1. #157 
2. #166 
3. #179 

### Issue description

I'm sending WebhookEvents to my local development environment (via ngrok) using PayPal's Webhooks. I created a webhook on ```developer.paypal.com``` under the SANDBOX WEBHOOKS. When I try to verify the WebhookEvent using the post data from the sandbox, I get a response of:

[('rsa routines', 'INT_RSA_VERIFY', 'bad signature')]

I can't see what I'm doing wrong. Here is the data I'm using, based on the http request from PayPal.

```
self.request.META = 
{'wsgi.multiprocess': False, 'HTTP_PAYPAL_AUTH_VERSION': 'v2', u'SCRIPT_NAME': u'', 'REQUEST_METHOD': 'POST', 'HTTP_PAYPAL_TRANSMISSION_ID': '266ae2c0-25ef-11e7-8be9-6b62a8a99ac4', 'PATH_INFO': u'/membership/payment/status/', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': '', 'HTTP_PAYPAL_TRANSMISSION_SIG': 'sce/6hKttWL/wrNuPpe7bC2M28Q/HseR71JLP38p5vDzGkgZdG1/UUIe1Pbt1+KvTAVXwhw3QhIxJr4m6NlFNCi2BYyUdZNkybyXr6PBiDu06gvOGFxSylZA9f44kQ09laS1aSWgjIIXZmdtqoxJughhFK8VbjqG5iGv4TxdWM0NxtVdO+Qiay1zyErRPvJNPjVOHnmFiFZtQ+Jhgg0xTRSxBYEwb1rJ2oL77yK8UzA0DULx1/Q6TYu6d2FeSpPVz8mkn2r45XifJ3709BeQKcxKqo3xX2IdYoz5QRmZO2Md+6oKMjxz01Vy5cGhfJOOiDDdRySSe5asD/R4bxVD0A==', 'UWSGI_SCHEME': 'https', 'CONTENT_LENGTH': '2080', 'HTTP_USER_AGENT': 'PayPal/AUHD-210.0-32002342', 'SERVER_NAME': 'api-staging.learn-skillz.com', 'REMOTE_ADDR': '173.0.82.126', 'HTTP_PAYPAL_CERT_URL': 'https://api.sandbox.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-aecacc47', 'wsgi.url_scheme': 'https', 'SERVER_PORT': '443', 'uwsgi.node': 'ip-172-31-20-197', 'DOCUMENT_ROOT': '/usr/share/nginx/html', 'HTTP_CONTENT_LENGTH': '2080', 'wsgi.input': <uwsgi._Input object at 0x7f4685fef708>, 'HTTP_HOST': 'api-staging.learn-skillz.com', 'wsgi.multithread': False, 'wsgi.version': (1, 0), 'HTTP_CONTENT_TYPE': 'application/json', 'HTTP_PAYPAL_TRANSMISSION_TIME': '2017-04-20T17:31:13Z', 'REQUEST_URI': '/membership/payment/status/', 'HTTP_ACCEPT': '*/*', 'HTTP_CORRELATION_ID': '244e869f840e0', 'wsgi.run_once': False, 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7f468721a030>, 'REMOTE_PORT': '38441', 'uwsgi.version': '1.9.17.1-debian', 'CONTENT_TYPE': 'application/json', 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>, u'CSRF_COOKIE': u'IPl21R3PXjGNvTTCXhSJZdAxoo1DjhnC', 'HTTP_PAYPAL_AUTH_ALGO': 'SHA256withRSA'}
```

```
self.request.data = '
{"resource": {"description": "this is aggreement description of paypal payment", "links": [{"href": "api.sandbox.paypal.com/v1/payments/billing-agreements/I-D75430VUDDYM", "method": "GET", "rel": "self"}], "agreement_details": {"num_cycles_remaining": "1", "next_billing_date": "2017-04-20T10:00:00Z", "num_cycles_completed": "0", "failed_payment_count": "0", "final_payment_due_date": "1970-01-01T00:00:00Z", "outstanding_balance": {"value": "0.00"}}, "payer": {"payment_method": "paypal", "status": "verified", "payer_info": {"shipping_address": {"city": "San Jose", "line1": "1 Main St", "recipient_name": "test buyer", "state": "CA", "postal_code": "95131", "country_code": "US"}, "first_name": "test", "last_name": "buyer", "email": "support-buyer@learn-skillz.com", "payer_id": "LUTSS7YKHHM8N"}}, "start_date": "2017-04-20T07:00:00Z", "state": "Active", "plan": {"payment_definitions": [{"charge_models": [{"amount": {"value": "0.00"}, "type": "TAX"}, {"amount": {"value": "0.00"}, "type": "SHIPPING"}], "type": "TRIAL", "amount": {"value": "0.00"}, "frequency": "Day", "cycles": "1", "frequency_interval": "1"}, {"charge_models": [{"amount": {"value": "0.00"}, "type": "TAX"}, {"amount": {"value": "0.00"}, "type": "SHIPPING"}], "type": "REGULAR", "amount": {"value": "29.99"}, "frequency": "Day", "cycles": "0", "frequency_interval": "1"}], "merchant_preferences": {"max_fail_attempts": "1", "setup_fee": {"value": "0.00"}, "auto_bill_amount": "YES"}, "curr_code": "USD", "links": []}, "shipping_address": {"city": "San Jose", "line1": "1 Main St", "recipient_name": "test buyer", "state": "CA", "postal_code": "95131", "country_code": "US"}, "id": "I-D75430VUDDYM"}, "event_type": "BILLING.SUBSCRIPTION.CREATED", "links": [{"href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-1CN58512SU554860M-3HH12985DY1848520", "method": "GET", "rel": "self"}, {"href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-1CN58512SU554860M-3HH12985DY1848520/resend", "method": "POST", "rel": "resend"}], "summary": "A billing subscription was created", "event_version": "1.0", "create_time": "2017-04-20T17:31:12.858Z", "id": "WH-1CN58512SU554860M-3HH12985DY1848520", "resource_type": "Agreement"}
'
```

```
WEBHOOK_ID = "0FM01498EV869870X"
```

```
import paypalrestsdk
response = paypalrestsdk.WebhookEvent.verify(
    transmission_id=self.request.META['HTTP_PAYPAL_TRANSMISSION_ID'],
    timestamp=self.request.META['HTTP_PAYPAL_TRANSMISSION_TIME'],
    webhook_id=WEBHOOK_ID,
    event_body=str(self.request.data),
    cert_url=self.request.META['HTTP_PAYPAL_CERT_URL'],
    actual_sig=self.request.META['HTTP_PAYPAL_TRANSMISSION_SIG'],
    auth_algo=self.request.META['HTTP_PAYPAL_AUTH_ALGO']
)
```

I also tried the following request(with variations in encode/decode), but in vain.

```
import paypalrestsdk
response = paypalrestsdk.WebhookEvent.verify(
    transmission_id=self.request.META['HTTP_PAYPAL_TRANSMISSION_ID'].encode('utf-8'),
    timestamp=self.request.META['HTTP_PAYPAL_TRANSMISSION_TIME'].encode('utf-8'),
    webhook_id=WEBHOOK_ID,
    event_body=str(self.request.data),
    cert_url=self.request.META['HTTP_PAYPAL_CERT_URL'].encode('utf-8'),
    actual_sig=self.request.META['HTTP_PAYPAL_TRANSMISSION_SIG'].encode('utf-8'),
    auth_algo=self.request.META['HTTP_PAYPAL_AUTH_ALGO'].encode('utf-8')
)
```

Can you please point me in the right direction?

**Comment by pp-randy** [comment]
Is this from the webhooks simulator?  If so, those will not validate. 
![image](https://cloud.githubusercontent.com/assets/6819909/25280027/23871ed2-266e-11e7-9990-d3dc98f31f27.png)

The other common cause would be the webhook event body is being rearranged or changed in some way `event_body=str(self.request.data)`.   The actual JSON string is what is validated against, so it needs to match exactly how it was sent.

**Comment by pp-randy** [comment]
The order of the values in the JSON string you provided do not match the order in my testing that does validate, so most likely `self.request.data` is not matching the original string sent to you. 

```
self.request.data = '
{"resource": {"description": "this is aggreement description of paypal payment", "links": [{"href": "api.sandbox.paypal.com/v1/payments/billing-agreements/I-D75430VUDDYM", "method": "GET", "rel": "self"}], "agreement_details": {"num_cycles_remaining": "1", "next_billing_date": "2017-04-20T10:00:00Z", "num_cycles_completed": "0", "failed_payment_count": "0", "final_payment_due_date": "1970-01-01T00:00:00Z", "outstanding_balance": {"value": "0.00"}}, "payer": {"payment_method": "paypal", "status": "verified", "payer_info": {"shipping_address": {"city": "San Jose", "line1": "1 Main St", "recipient_name": "test buyer", "state": "CA", "postal_code": "95131", "country_code": "US"}, "first_name": "test", "last_name": "buyer", "email": "support-buyer@learn-skillz.com", "payer_id": "LUTSS7YKHHM8N"}}, "start_date": "2017-04-20T07:00:00Z", "state": "Active", "plan": {"payment_definitions": [{"charge_models": [{"amount": {"value": "0.00"}, "type": "TAX"}, {"amount": {"value": "0.00"}, "type": "SHIPPING"}], "type": "TRIAL", "amount": {"value": "0.00"}, "frequency": "Day", "cycles": "1", "frequency_interval": "1"}, {"charge_models": [{"amount": {"value": "0.00"}, "type": "TAX"}, {"amount": {"value": "0.00"}, "type": "SHIPPING"}], "type": "REGULAR", "amount": {"value": "29.99"}, "frequency": "Day", "cycles": "0", "frequency_interval": "1"}], "merchant_preferences": {"max_fail_attempts": "1", "setup_fee": {"value": "0.00"}, "auto_bill_amount": "YES"}, "curr_code": "USD", "links": []}, "shipping_address": {"city": "San Jose", "line1": "1 Main St", "recipient_name": "test buyer", "state": "CA", "postal_code": "95131", "country_code": "US"}, "id": "I-D75430VUDDYM"}, "event_type": "BILLING.SUBSCRIPTION.CREATED", "links": [{"href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-1CN58512SU554860M-3HH12985DY1848520", "method": "GET", "rel": "self"}, {"href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-1CN58512SU554860M-3HH12985DY1848520/resend", "method": "POST", "rel": "resend"}], "summary": "A billing subscription was created", "event_version": "1.0", "create_time": "2017-04-20T17:31:12.858Z", "id": "WH-1CN58512SU554860M-3HH12985DY1848520", "resource_type": "Agreement"}
'
```

**Comment by dhruvsingh** [comment]
Not using the webhooks simulator.
But the webhooks under paypal sandbox account.
I tried passing in ```self.request.data``` as it is but then the expected input is supposed to be a string as listed [here](https://github.com/paypal/PayPal-Python-SDK/blob/master/samples/notification/webhook-events/verify_webhook_events.py#L12).

Do you think I should try making ```self.request.data``` as an [OrderedDict](https://docs.python.org/2/library/collections.html#collections.OrderedDict)?

**Comment by pp-randy** [comment]
Do you have access to the raw request body? Such as  [`self.request.body`](https://cloud.google.com/appengine/docs/standard/python/tools/webapp/requestdata).  If so, are you then able to [`decode` to utf-8](https://docs.python.org/3/library/stdtypes.html#bytes.decode)?

**Comment by dhruvsingh** [comment]
Yes, I have access to raw ```self.request.body```, and as I mentioned in the first comment, I tried to do a ```decode()``` on the request body, but in vain.
I got the same error.

[Docs](https://docs.python.org/3/library/stdtypes.html#bytes.decode) for decode list that by default the encoding being used is 'utf-8', so I called it without any params.

The output is as follows:

```
ipdb> WEBHOOK_ID = "6A506544NG7149503"

ipdb> response = paypalrestsdk.WebhookEvent.verify(
                transmission_id=self.request.META['HTTP_PAYPAL_TRANSMISSION_ID'],
                timestamp=self.request.META['HTTP_PAYPAL_TRANSMISSION_TIME'],
                webhook_id=WEBHOOK_ID,
                event_body=str(self.request.data).decode('utf-8'),
                cert_url=self.request.META['HTTP_PAYPAL_CERT_URL'],
                actual_sig=self.request.META['HTTP_PAYPAL_TRANSMISSION_SIG'],
                auth_algo=self.request.META['HTTP_PAYPAL_AUTH_ALGO']
            )
[('rsa routines', 'INT_RSA_VERIFY', 'bad signature')]
```

**Comment by pp-randy** [comment]
Are you using flask? If so, try this method found in the answer  http://stackoverflow.com/questions/10999990/get-raw-post-body-in-python-flask-regardless-of-content-type-header

Also please provide the string being created so I can check its order.

**Comment by pp-randy** [comment]
I did run some testing just to ensure everything SDK side was working.  
Double check your `WEBHOOK_ID` to make sure it matches that of your listener.  At this point I'm fairly certain something happening with the request body.

**Comment by dhruvsingh** [comment]
@pp-randy thanks a bunch. :+1: 

The request body in Django needs to be used as ```request.body``` and NOT ```request.data```.
Doing ```str(request.body)``` does not help, and neither will ```str(request.body).decode('utf-8')```.

The SDK works perfect. I think the documentation or the example [here](https://github.com/paypal/PayPal-Python-SDK/blob/master/samples/notification/webhook-events/verify_webhook_events.py#L12) needs to list the common gotchas with Django and Flask

**Comment by mwcbrent** [comment]
This thread was helpful for me to find a solution.  I wanted to note my solution as well.  The request body being sent back to PayPal for verification had been parsed into a dict in my case.  I was using Django Rest Framework for my webhook view that would process the inbound webhook as `request.data` which will not validate.  I found that by removing Rest Framework from my view allowed me to get access directly to `request.body` and the following line worked for me `json.loads(request.body.decode('utf-8'))`.

**Comment by cubicova17** [comment]
Just in case somebody will encounter similar error:
we were able to solve the same issue when removed
`from __future__ import absolute_import, division, print_function, unicode_literals` in the beginning of the file that contained webhook verification routine.
Explanation: we are in the the process of migrating from Python2.7 to Python3 and `unicode_literals` import made stings different on verification.

**Comment by jassim4023** [comment]
> I found that by removing Rest Framework from my view allowed me to get access directly to `request.body` 

Thanks for poiting out that. I used DRF too and changing it to a django view worked. Also passing just  request.body.decode('utf-8') to the event_body did the verification for me.

**Comment by trantinan2512** [comment]
For anyone wanting to use it with DRF:
- To Access the raw body using `request.stream.body`
- passing `event_body=request.stream.body.decode('utf-8')` works for me

Packages version:
```django==2.2.5
djangorestframework==3.10.3
paypalrestsdk==1.13.1
```
