### ISSUE TITLE
'An unknown error occurred' when trying to create a payment

### ISSUE THREAD

**Issue by jinchuika** [paypal/PayPal-Python-SDK#198]
### General information

* SDK/Library version: Python .12.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: f65dc62e9d3c2
* Language, language version, and OS: Python 3.5 on Ubuntu Server 16.04

When ever I try to make a payment using credit card (the one provided in docs for testing purposes), it returns the next error:
`{'name': 'UNKNOWN_ERROR', 'message': 'An unknown error occurred.', 'information_link': 'https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR', 'debug_id': 'f65dc62e9d3c2'}`

I literaly copy/pasted my method from another project I used in the same account that worked some months ago (but I wasn't able to test again).

**Comment by pp-randy** [comment]
Skip to the bottom of step 4 in this FAQ and use the Credit Card number generator https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413.

The credit cards in docs have an issue here: https://github.com/paypal/PayPal-REST-API-issues/issues/22

**Comment by pp-randy** [comment]
Closing the issue since the above should help. Let me know if you experience further issues.

**Comment by jinchuika** [comment]
I managed to solve it tweaking the method you suggested. I went to https://developer.paypal.com/ and added an account then in the "Sandbox" section. Then clicked on the "Profile" link below the created account. In the displayed window, there's a tab called "Funding", where my testing credit card was. Finally worked using that credit card.
