### ISSUE TITLE
Add clear error message if invalid mode is configured

### ISSUE THREAD

**Issue by NazarTopolsky** [paypal/PayPal-Python-SDK#202]
### General information

* SDK/Library version: 1.12.0
* Environment: Any (see description)
* Python: 2.7.10

### Issue description

Currently, it is possible to pass any gibberish to `paypalrestsdk.configure` as `mode`, and it will happily accept it. Creating payment with such gibberish mode doesn't work, obviously.

Minimal example:

    paypalrestsdk.configure({
        "mode": "gibberish mode",  # offending line
        "client_id": settings.PAYPAL_CLIENT_ID,
        "client_secret": settings.PAYPAL_CLIENT_SECRET
    })
    payment_info = {
        "intent": "sale",
        "payer": {"payment_method": "paypal"},
        "transactions": [{
            "item_list": {"items": [{"name": "item",
                                              "sku": "item",
                                              "price": "1.00",
                                              "currency": "USD",
                                              "quantity": 1}]},
            "amount": {"total": "1.00",
                              "currency": "USD"},
        }],
        "redirect_urls": {"return_url": '/',
                                  "cancel_url": '/cancel/'}
    }
    payment = paypalrestsdk.Payment(payment_info)
    payment.create()

The code above yields a following error:

    Traceback (most recent call last):
    File "/projects/paypal_example.py", line 36, in <module>
        payment.create()
    File "/python_env/local/lib/python2.7/site-packages/paypalrestsdk/resource.py", line 163, in create
        new_attributes = self.api.post(self.path, self.to_dict(), headers, refresh_token)
    File "/python_env/local/lib/python2.7/site-packages/paypalrestsdk/api.py", line 272, in post
        return self.request(util.join_url(self.endpoint, action), 'POST', body=params or {}, headers=headers or {}, refresh_token=refresh_token)
    File "/python_env/local/lib/python2.7/site-packages/paypalrestsdk/util.py", line 22, in join_url
        url = re.sub(r'/?$', re.sub(r'^/?', '/', path), url)
    File "/python_env/lib/python2.7/re.py", line 155, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or buffer

As I understand, in this case `Api` object uses default endpoint from `paypalrestsdk.config.__endpoint_map__`, but uses `.get`, so incorrect mode yields `None`.

I think it would be better to fail earlier, say, in `Api.__init__`, and throw something like

    ValueError: incorrect mode; expected "sandbox" or "live"

instead of spilling internals like that.

I understand that docs explicitly specify that only "sandbox" or "live" settings can be used, but readable error message is always an improvement.

**Comment by trainerbill** [comment]
@NazarTopolsky What about if not "sandbox" then "live".  so unless you specifically send "sandbox" it is "live".

**Comment by NazarTopolsky** [comment]
@trainerbill Sorry for the late response.

I am not sure that is a very good idea since it violates a principle of least surprise. I'd have my program crash early and loudly rather than doing something that doesn't necessarily make sense.

**Comment by skudriashev** [comment]
I think this one can be closed...
