### ISSUE TITLE
PPsubscribe in heroku app shows SSL Error

### ISSUE THREAD

**Issue by jrsenthilk23** [paypal/PayPal-Python-SDK#203]
Just clicked on the http://ppsubscribe.herokuapp.com/ and logged in using "customer" and "cpass" but i get a SSL error. Is it being maintained still?

This is the error:
requests.exceptions.SSLError
SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Thanks

### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by xiaoleih41** [comment]
This is not a PayPal site. Please contact the site directly for this site specific question.

**Comment by xiaoleih41** [comment]
Close this thread as it's not a PayPal issue.

**Comment by sposs** [comment]
Are you kidding? This web site is promoted in the documentation! https://github.com/paypal/PayPal-Python-SDK/tree/master/samples/subscription/ppsubscribe
