### ISSUE TITLE
How to avoid repeated authorisation by catching the token till it expires?

### ISSUE THREAD

**Issue by cijo7** [paypal/PayPal-Python-SDK#209]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

The following is the logs from a normal request with the SDK.
INFO:paypalrestsdk.api:Request[POST]: https://api.sandbox.paypal.com/v1/oauth2/token
INFO:paypalrestsdk.api:Response[200]: OK, Duration: 4.636123s.
INFO:paypalrestsdk.api:PayPal-Request-Id: xxxxxxx-xxxx-xxxxx-xxxxx-xxxxxxxxxxxxx
INFO:paypalrestsdk.api:Request[POST]: https://api.sandbox.paypal.com/v1/payments/billing-agreements
INFO:paypalrestsdk.api:Response[201]: Created, Duration: 6.574508s.
How can i avoid repeated authorizations by caching the Bearer token so that a new payment url could be obtained with a single request. Is there a built-in way?

**Comment by xiaoleih41** [comment]
The token lasts 8 hours. You can't extend beyond that. It's an industry standard for security reason. Please refer [this](https://developer.paypal.com/docs/integration/direct/paypal-oauth2/?mark=oauth%202.0) on how PayPal using OAuth 2.0 token.

**Comment by cijo7** [comment]
Yes, I know that the token is valid only for about few hours. And my question is how to reuse the token in that period instead of requesting it again since the last token received has not expired?

**Comment by xiaoleih41** [comment]
You can cache it in your session or whatever method you prefer and use it before it gets expired.

**Comment by cijo7** [comment]
Yes. But how can I tell PayPal Python SDK to use my existing token without making a request for new one? How should I pass the token value?

**Comment by xiaoleih41** [comment]
Please add this
````
import paypalrestsdk
paypalrestsdk.configure({
  "mode": "sandbox", # sandbox or live
  "token": "your_access_token" })
````

**Comment by xiaoleih41** [comment]
close this issue due to inactivity. Please resubmit when you have additional questions.
