### ISSUE TITLE
Refunds not working

### ISSUE THREAD

**Issue by HugoSPT** [paypal/PayPal-Python-SDK#210]
### General information
Not able to create refunds

* SDK/Library version: 1.12.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: Python 3.6.0 on OS X El Capitan 10.11.6

### Issue description
When I try to create a refund I get one of two errors:
1. Calling `Sale.refund({"amount": {"currency": "USD", "total": amount['value']}})` returns a PayPal errors saying I cannot create partial refunds;
2. Calling `Sale.refund()` I got a library errors saying I need to provide some attributes.

Looking for the API 2. shouldn't be a problem since not passing attributes means create a full refund.

How can I circumvent this issue?

Thank you in advance.

**Comment by xiaoleih41** [comment]
Which transaction are you trying to refund? What's the `DebugId` for the API call?

**Comment by HugoSPT** [comment]
Ok, maybe I found the problem... Here is the transaction (got from Billing Agreement):

```
{
  'transaction_id': '6K173167GG205294C',
  'status': 'Unclaimed',
  'transaction_type': 'Recurring Payment',
  'amount': {
    'currency': 'USD',
    'value': '9.00'
  },
  'fee_amount': {
    'currency': 'USD',
    'value': '0.00'
  },
  'net_amount': {
    'currency': 'USD',
    'value': '9.00'
  },
  'payer_email': 'billing-buyer@memrise.com',
  'payer_name': 'Test Buyer',
  'time_stamp': '2017-06-26T16:30:52Z',
  'time_zone': 'GMT'
}
```

Maybe the problem is the transaction status being `Unclaimed`?

The Debug ID is `929556e6e3bcc`

**Comment by xiaoleih41** [comment]
yes. you can only refund a `completed` transaction. You can go into the account and **deny** or **accept** the payment.

**Comment by xiaoleih41** [comment]
Close this issueas the question has been answered.
