### ISSUE TITLE
Constat 500 Internal Server Error when using the Payouts API

### ISSUE THREAD

**Issue by AlecsGherghel** [paypal/PayPal-Python-SDK#215]
### General information

* SDK/Library version: 1.13.1
* Environment: sandbox
* `PayPal-Debug-ID` values: c1932bd0c106d, 39ed501928fc4
* Language, language version, and OS: python 2.7.11 on Ubuntu 14.10

### Issue description
Hey! I'm trying to create a batch payout in sandbox, using only one recipient. The payload i'm using for the Payout object looks like this:
`{
   'items':[
      {
         'note':'Thank You!',
         'amount':{
            'currency':'USD',
            'value':'0.99'
         },
         'sender_item_id':'201403140002',
         'recipient_type':'EMAIL',
         'receiver':'x@x.eu'
      }
   ],
   'sender_batch_header':{
      'email_subject':'You have a payment from X!',
      'sender_batch_id':'ATZBZEGEIOMT'
   }
}`

Constantly getting 500 Internal Server Error with the following message:
`{
   "name":"INTERNAL_ERROR",
   "message":"An internal service error has occurred.",
   "debug_id":"d2f960dd11018",
   "information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"
}`

**Comment by chris-trotter** [comment]
Known unresolved issue [915](https://github.com/paypal/PayPal-PHP-SDK/issues/915)

**Comment by pp-randy** [comment]
I am tracking this issue here https://github.com/paypal/PayPal-REST-API-issues/issues/130.  
 Please follow https://github.com/paypal/PayPal-REST-API-issues/issues/130 for further updates.
