### ISSUE TITLE
Dispute API?

### ISSUE THREAD

**Issue by jleclanche** [paypal/PayPal-Python-SDK#216]
It doesn't look like this sdk implements the Dispute API.

I'd like to be able to do eg. `Dispute.find("PP-000-042-580-XXX")` and get a Dispute object.

**Comment by xiaoleih41** [comment]
There's no **dispute object** in PayPal API. PayPal can send you [IPN](https://developer.paypal.com/docs/classic/products/instant-payment-notification/) or [webhooks](https://developer.paypal.com/docs/integration/direct/webhooks/) or both. You can do case search in your saved database.  The information on dispute related webhooks is located [here](https://developer.paypal.com/docs/integration/direct/webhooks/event-names/#customer-disputes) .

**Comment by jleclanche** [comment]
What's this then? https://developer.paypal.com/docs/api/customer-disputes/#disputes_get-dispute

**Comment by xiaoleih41** [comment]
It's limited release API. It is designed for large partner and contracted merchants. It is not included in this SDK at this time. You may want to check with your assigned account manager to get approval for the live usage of this API first before spending time on this API. In the meantime, I would suggest webhooks and IPN which is available to general public.

**Comment by jleclanche** [comment]
I mean, I'm working on a django integration: https://github.com/dj-stripe/dj-paypal

Dispute object creation is what's missing in there right now.

**Comment by xiaoleih41** [comment]
Dispute API and Webhooks for dispute API are both limited released APIs. It is not available for general public. Once the API is available for general public, we will look into adding it to the SDK.  I am checking into the possibility of getting you access these APIs live at this stage.

**Comment by jleclanche** [comment]
It's okay, I don't particularly need access to them, I was just hoping for support in the sdk.

The Dispute webhooks are actually available at least in Sandbox mode.

**Comment by xiaoleih41** [comment]
Yes, they both are under review and testing stage. Once it's available for general public, we will work on adding them to the SDK.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
