### ISSUE TITLE
Api constructor won't allow mode in create_with_paypal_security_test.py

### ISSUE THREAD

**Issue by davidlmontgomery** [paypal/PayPal-Python-SDK#220]
### General information

* SDK/Library version: 1.13.1
* Environment: Sandbox

### Issue description

The front page of this repository points out the importance of checking for a compliant version of TLS, and directs developers to https://github.com/paypal/PayPal-Python-SDK/blob/master/samples/payment/create_with_paypal_security_test.py to check this issue.

This script sets the mode to "security-test-sandbox", which config.py's \_\_endpoint_map\_\_ maps to "https://test-api.sandbox.paypal.com/". 

But the Api constructor contains the following check:
```python
  if self.mode != "live" and self.mode != "sandbox":
    raise exceptions.InvalidConfig("Configuration Mode Invalid", "Received: %s" % (self.mode), "Required: live or sandbox")
```
Thus, the sample code cannot work. A mode of "security-test-sandbox" is not allowed.

The following change seems to give the desired results:
```python
paypal.configure({
    "mode": "sandbox",
    "endpoint": paypal.config.__endpoint_map__["security-test-sandbox"],
    "client_id": "<CLIENT_ID>",
    "client_secret": "<CLIENT_SECRET>"
})
```
Alternatively, the constructor could allow a mode of "security-test-sandbox".

**Comment by pp-randy** [comment]
Sorry about that, I will take a look.  You should just be able to test in sandbox since TLS 1.2 is being enforced.

**Comment by davidlmontgomery** [comment]
That's great to know about TLS 1.2 being enforced in sandbox. That's what I was seeing at https://www.ssllabs.com/ssltest/, but I am new to this, and it didn't seem to fit with the readme and the test script, so I was still investigating. Knowing this saved me some time. Maybe readme (github frontpage) should be updated to reflect this.

**Comment by bluk** [comment]
Thanks for reporting the issue. I opened a PR for this: https://github.com/paypal/PayPal-Python-SDK/pull/222 which should resolve this issue.
