### ISSUE TITLE
Dependencies are not available 

### ISSUE THREAD

**Issue by santhoshlfms** [paypal/PayPal-Python-SDK#221]
### Issue description

Dependencies braintreehttp 1.4.0 is not available in the registry how to get 1.4.0 version and also paypalrestsdk 2.0.0b2 is not available in registry 

![image](https://user-images.githubusercontent.com/5546770/31369821-9bcace94-ada4-11e7-8854-30b8c32793f9.png)

**Comment by xiaoleih41** [comment]
We are looking into this.

**Comment by sdcoffey** [comment]
Thanks for pointing this out @santhoshlfms, `2.0.0b3` is now available with a fix for the upstream dependency. Please try out the new SDK and leave us some feedback!
