### ISSUE TITLE
Show all available versions on PyPI

### ISSUE THREAD

**Issue by andreif** [paypal/PayPal-Python-SDK#224]
The beta is currently broken (#223) and it's not clear what version is stable without running pip. I believe it's possible to configure the package on PyPI for showing all versions.

**Comment by sdcoffey** [comment]
Hey @andreif,

Thanks for bringing this up. We can definitely unhide a few of the most recent versions if you think that would help. For the time being, I'll unhide all beta versions and the most recent stable version. When you're able to address the comment in the PR referenced above, I'll merge and do another release.

**Comment by andreif** [comment]
Thanks, that's perfect!
