### ISSUE TITLE
sync api addition

### ISSUE THREAD

**Issue by Bobspadger** [paypal/PayPal-Python-SDK#228]
Hi

Do you have a roadmap for adding in the new sync api ?

Thanks

Alex

**Comment by xiaoleih41** [comment]
We are working on a newer version of SDKs. It's still in [beta](https://github.com/paypal/PayPal-Python-SDK/tree/2.0-beta/paypalrestsdk). sometime in the future, we will be adding the new sync api to that version of SDK.

**Comment by Bobspadger** [comment]
Thanks for the info - do you have an ETA for the addition of the sync api to the sdk?

**Comment by xiaoleih41** [comment]
We do have yet.  I will check with our internal team and get back to you on that.

**Comment by pp-randy** [comment]
@Bobspadger we discussed this further and will try to get Order and Sync APIs added later today if all goes accordingly.

**Comment by Bobspadger** [comment]
@pp-randy  WOW! that would be amazing, I was just looking to see if I could extend it myself, but I'll wait I think!

thats fantastic :) thanks

**Comment by Bobspadger** [comment]
how is this coming along? I'm happy to get testing with it :)

**Comment by pp-randy** [comment]
The pulls are in for .Net, the team is still following up on Python.

**Comment by Bobspadger** [comment]
cool - thanks for the info :)

**Comment by pp-randy** [comment]
The pull for Sync is available for review https://github.com/paypal/PayPal-Python-SDK/pull/230.

**Comment by Bobspadger** [comment]
Thanks, I'll be looking at this later today :)

**Comment by Bobspadger** [comment]
All looking good so far on this, I've got Sync running quite nicely now.

There are questions outstanding on the object returned being awkward to use, and the time lag, but thats outside of the scope of this.

Good work!

**Comment by bluk** [comment]
Thanks for the feedback. The original issue here is solved with the [v2 of the SDK](https://github.com/paypal/PayPal-Python-SDK/tree/2.0-beta/) and the suggestion for the get is opened as https://github.com/braintree/braintreehttp_python/issues/1 . If you have additional feedback, please open a new issue. Thanks.
