### ISSUE TITLE
Sync API: DataTypes returned

### ISSUE THREAD

**Issue by Bobspadger** [paypal/PayPal-Python-SDK#239]
* SDK/Library version: 2.0 beta

### Issue description

The Sync API is returning data as expected, and this is brilliant.

I have a quick question on the datatypes being returned which happen to be `braintreehttp.http_response`

They have dot notation access, which is great, but I can't see if they have any equivalent to pythons `dictionary.get('key', None)` method to stop me from having to write lots of 

```python
try:
    currency_code = transaction.transaction_amount.currency_code
except AttributeError:
    currency_code = None
```

Can you let me know if there are methods to turn these into dictionaries etc, I can't seem to make this happen.

Thanks

**Comment by sdcoffey** [comment]
Hey @Bobspadger,

Thanks for the feedback! I think that's a reasonable thing to expect on the result object. I've [opened an issue in BraintreeHttp](https://github.com/braintree/braintreehttp_python/issues/1) to address this. Feel free to comment and update that with other feedback. In the meantime, I'd suggest just inspecting the result object to get a sense of the shape of the data, and then write your code 

Thanks again for the feedback!

**Comment by Bobspadger** [comment]
Thats brilliant, thanks.

I've currently got it all running (nice!) but the code is really, really ugly due to not all elements of a group being returned on every transaction,

there are so many Try / Except blocks its unbelievable :)

**Comment by xiaoleih41** [comment]
@Bobspadger I am closing this issue and please follow the new issue instead going forward.
