### ISSUE TITLE
How to get payment.execute error?

### ISSUE THREAD

**Issue by alexturpin** [paypal/PayPal-Python-SDK#245]
### General information

* SDK/Library version: 1.13.1
* Environment: Sandbox & production
* `PayPal-Debug-ID` values: N/A
* Language, language version, and OS: Python 3.6.3, Ubuntu 16.04

### Issue description

When `payment.execute` fails and returns `False`, how can we get more info about what happened? [The sample code](https://github.com/paypal/PayPal-Python-SDK/blob/master/samples/payment/execute.py) says to use `payment.error`. At least for me that raises a `TypeError: 'dict' object is not callable`. Doing `payment['error']` instead raises a `KeyError`. I had a look at the `payment` object and it doesn't look like there is any error information in it.

Any other way to obtain that information?

**Comment by xiaoleih41** [comment]
Could you please give me the exact request that you have sent that has caused this `TypeError:  'dict' object is not callable`?  Do you have a debugID?

**Comment by alexturpin** [comment]
Hi Xiaolei,

I apologize. I had another look today and it turns out this is user error. This is what I get for filling bug reports at 11pm. Thanks for taking the time to answer, sorry again!
