### ISSUE TITLE
Payment object cannot be serializable.

### ISSUE THREAD

**Issue by pons1991** [paypal/PayPal-Python-SDK#248]
Whenever I am creating a payment, There is an object "payment" is being created. 

I am not able to make it as a JSON. Whenever I am trying to make it serialize, Its showing "payment cannot be serializable"

Any Idea where I am missing?

**Comment by bluk** [comment]
Can you give an example of the code you are trying?

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please resubmit when you have additional info.
