### ISSUE TITLE
Docs for 2.0 RC are wrong

### ISSUE THREAD

**Issue by rfleschenberg** [paypal/PayPal-Python-SDK#249]
https://github.com/paypal/PayPal-Python-SDK/blob/2.0-beta/docs/Migrating.md

```python
env = paypal.PayPalEnvironment(client_id, client_secret, mode=paypalrestsdk.PayPalEnvironment.SANDBOX)
```

This references ``paypalrestsdk.PayPalEnvironment.SANDBOX``, but that object is not imported anywhere. Looking at the source, such a thing does not seem to exist anywhere. I guess this should be something like this?

```python
env = paypal.environment.SandboxEnvironment(client_id, client_secret)
```

**Comment by rfleschenberg** [comment]
```python
client = paypal.PayPalHttpClient(environment=env)
```

This is also wrong. I guess it should be
```python
client = paypal.paypal_http_client.PayPalHttpClient(environment=env)
```

**Comment by bluk** [comment]
I fixed the documentation with the renamed namespaces. If you have any other feedback, please let us know. Thanks.
