### ISSUE TITLE
Transfer money from my PayPal to another

### ISSUE THREAD

**Issue by lgnorance** [paypal/PayPal-Python-SDK#255]
### General information

* SDK/Library version: 2.0
* Environment: Sandbox

### Issue description

I am looking to create a Python Script in order to transfer money from a linked PayPal card in my account to another account.

I have searched this GitHub repository and PayPal Documentation, but can't seem to find if the PayPal Python SDK supports this function or if it I can do it via some other means. Would someone be able to point me into the right direction?

**Comment by xiaoleih41** [comment]
You cannot pay yourself or do cash advance. That will violate the creditcard rules. PayPal doesn't support this function.

**Comment by lgnorance** [comment]
If I log into PayPal, I am able to use the Send money to friends/family feature to send money from a debit card. I'm looking to create a script that completes the same function.

**Comment by xiaoleih41** [comment]
The personal payment feature is not available through REST API  to general public. You may look into venmo.com instead which is a PayPal company.

**Comment by xiaoleih41** [comment]
Close the issue as the question has been given.
