### ISSUE TITLE
Create Reference Transactions Endpoint manager.

### ISSUE THREAD

**Issue by agutierrezrodriguez** [paypal/PayPal-Python-SDK#257]
### General information

* SDK/Library version: 1.12.0
* Environment: Sandbox and Live
* Language, language version, and OS: Python 2.7 with virtualenv on Arch Linux.

### Issue description
Implement reference transactions endpoint to this library (/v1/billing-agreements/).
https://developer.paypal.com/docs/limited-release/reference-transactions/

**Comment by xiaoleih41** [comment]
Please specify your question.

**Comment by agutierrezrodriguez** [comment]
There isn't any question.

This library hasn't reference transactions endpoint (/v1/billing-agreements/) objects

**Comment by xiaoleih41** [comment]
You cannot reference transaction directly on REST API. Please consider to integrate Braintree or contact the local sales team of your region. There may be some integration guide on reference transaction for REST API available on case by case basis. We are building the newer version of billing agreement for REST API which will include this option.

**Comment by agutierrezrodriguez** [comment]
Any progress with this?

**Comment by advance512** [comment]
Hi there, I'd also like some information about this.

Our use case is simple: we want to charge based on usage. Metered-payment.
I thought a billing agreement would be sufficient, but it seems that the balance cannot be increased except by 20% every 180 days, and I'm not sure how we can charge less than the agreed upon recurring payment amount. Seems like Reference Transactions is the way to go. 

Any idea when this will be supported?

**Comment by advance512** [comment]
Hi guys,

I added an implementation of AgreementTokens and Agreements.
https://github.com/selectom/PayPal-Python-SDK

We're currently working on getting this feature enabled for our account, but it works perfectly with our sandbox account.

**Comment by sucithrashanu** [comment]
@agutierrezrodriguez 
Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check PayPal Community  (https://www.paypal-community.com )and  MTS ( https://paypal.com/mts )
Thanks!
