### ISSUE TITLE
can't get payment history

### ISSUE THREAD

**Issue by grepwood** [paypal/PayPal-Python-SDK#264]
### General information

* SDK/Library version: 1.13.1
* Environment: Production
* `PayPal-Debug-ID` values: what? where?
* Language, language version, and OS: Python 3.6, Gentoo Linux

### Issue description

I have the following code:
```
#!/usr/bin/env python3.6
import paypalrestsdk
paypalrestsdk.configure({"mode": "live", "client_id": "not_telling", "client_secret": "not_telling"})
payment_history = paypalrestsdk.Payment.all({"count": 10})
payment_history.payments
```

According to examples in the readme, this should get me 10 last transactions, but it doesn't get me squat. I tried to call `paypalrestsdk.Payment.find("insert_transaction_id_that_I_got_from_paypal_dashboard")` but it threw an exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mdec/.local/lib64/python3.6/site-packages/paypalrestsdk/resource.py", line 110, in find
    return cls(api.get(url, refresh_token=refresh_token), api=api)
  File "/home/mdec/.local/lib64/python3.6/site-packages/paypalrestsdk/api.py", line 268, in get
    return self.request(util.join_url(self.endpoint, action), 'GET', headers=headers or {}, refresh_token=refresh_token)
  File "/home/mdec/.local/lib64/python3.6/site-packages/paypalrestsdk/api.py", line 171, in request
    return self.http_call(url, method, data=json.dumps(body), headers=http_headers)
  File "/home/mdec/.local/lib64/python3.6/site-packages/paypalrestsdk/api.py", line 214, in http_call
    return self.handle_response(response, response.content.decode('utf-8'))
  File "/home/mdec/.local/lib64/python3.6/site-packages/paypalrestsdk/api.py", line 231, in handle_response
    raise exceptions.ResourceNotFound(response, content)
paypalrestsdk.exceptions.ResourceNotFound: Failed. Response status: 404. Response message: Not Found. Error message: {"name":"INVALID_RESOURCE_ID","message":"Requested resource ID was not found.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"is_it_safe_to_post_this?"}
```

The results of using this SDK are really underwhelming to say the least. How can I search my PayPal payments (incoming payments actually) history based on payment comments? I want to search for payments which comment start with "payment for customer XYZ". Doing this would save a lot of time and energy.

**Comment by johnroper100** [comment]
+1

**Comment by mitchellbregman** [comment]
Were you ever able to solve this? @grepwood

**Comment by grepwood** [comment]
@mitchellbregman Yes, but not with this garbage SDK. Use https://gist.github.com/grepwood/839a58bd1846e02c2cfa72d026bd77a9 instead. Don't forget to provision your own way to load client_id and secret_id.

**Comment by sucithrashanu** [comment]
@grepwood 
If you Are still facing this issue. Please provide latest PayPal-Debug-ID.

Thanks
