### ISSUE TITLE
missing payout api support?

### ISSUE THREAD

**Issue by jiamo** [paypal/PayPal-Python-SDK#267]
* SDK/Library version: 2.0.0-rc2
It seem to me the latest sdk don't support payout?  Like the content in this url: https://developer.paypal.com/docs/api/payments.payouts-batch/v1/

Does it mean I must do api in curl or wrap by myself? Or do you have plan support the payout api?

I also find this example in master branch https://github.com/paypal/PayPal-Python-SDK/blob/master/samples/payout/create.py

**Comment by joantune** [comment]
Take a look at those samples and https://github.com/paypal/PayPal-Python-SDK/blob/50eb6d9892329cf391b0442ccfd497afe3eccb4a/paypalrestsdk/payments.py#L223

**Comment by sucithrashanu** [comment]
@jiamo Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check PayPal Community  (https://www.paypal-community.com )and  MTS ( https://paypal.com/mts )

Thanks!
