### ISSUE TITLE
Payment Capture Fails Intermittently

### ISSUE THREAD

**Issue by penguinstampede** [paypal/PayPal-Python-SDK#271]
At times I receive a PAYER_CANNOT_PAY error when trying to capture an already-authorized transaction.  My understanding is that PAYER_CANNOT_PAY should be returned in the authorization step, and after that the funds are already on hold.

Sometimes re-running the capture using the SDK works, but most of the time the re-capture fails as well.

That being said, in Paypal I'm able to still manually capture these authorizations.  I'm not sure what's happening here especially since most of the time auth-and-capture works without issue.

Here are a couple Exceptions with Debug IDs:

```
Exception: {u'message': u'Combination of payer and payee settings mean that this buyer cannot pay this seller.', u'debug_id': u'5b3f62923e71a', u'name': u'PAYER_CANNOT_PAY', u'information_link': u'https://developer.paypal.com/docs/api/payments/#errors'}
```

```
Exception: {u'message': u'Combination of payer and payee settings mean that this buyer cannot pay this seller.', u'debug_id': u'3cc5113d26c19', u'name': u'PAYER_CANNOT_PAY', u'information_link': u'https://developer.paypal.com/docs/api/payments/#errors'}
```

**Comment by akempe** [comment]
@penguinstampede did you get anywhere with this? I've long been having this exact issue and no one at PayPal is able to fix it or provide more insight.

**Comment by prakash-gangadharan** [comment]
@penguinstampede,  can you please recent instance?

**Comment by prakash-gangadharan** [comment]
@penguinstampede, do you have recent `PayPal-Debug-ID` for this issue to check this further?
