### ISSUE TITLE
No payment history

### ISSUE THREAD

**Issue by apepenkov** [paypal/PayPal-Python-SDK#280]
### General information

* SDK/Library version: 1.13.1
* Environment: Producion
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: Python 3.7 Windows 10 x64

### Issue description

![изображение](https://user-images.githubusercontent.com/39992738/60088910-22469000-9748-11e9-945d-82c5a656a7a9.png)
Cannot see any payment via AIP
![изображение](https://user-images.githubusercontent.com/39992738/60088785-eb707a00-9747-11e9-805e-aed0fd093999.png)

**Comment by sucithrashanu** [comment]
@apepenkov 
I work around the sample snippet. I got the list of payment history. Please revert us back if issue occur.

<img width="1667" alt="Payment_history" src="https://user-images.githubusercontent.com/11882622/67546097-01ec0980-f719-11e9-95d5-ba04cbc8012b.png">
