### ISSUE TITLE
Get requests made by SDK has bodys with 'null' string

### ISSUE THREAD

**Issue by bronvic** [paypal/PayPal-Python-SDK#281]
### General information

* SDK/Library version: 1.13.1 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description
I found that [here](https://github.com/paypal/PayPal-Python-SDK/blob/master/paypalrestsdk/api.py#L171) parameter body can be `None`. And it will be `None` if you calling `api request` method from [`get`](https://github.com/paypal/PayPal-Python-SDK/blob/master/paypalrestsdk/api.py#L268).

So when you call `data=json.dumps(body)` with `body=None` you will get `'null'` string and after all it will become body of GET request

This is acceptable, but does not appear to be expected behavior

**Comment by sucithrashanu** [comment]
@bronvic 

It would be great can you give me the recent PayPal-Debug-ID and Environment? 

Thanks

**Comment by sucithrashanu** [comment]
@bronvic 
Closed the issue due to Inactive. If any query please reopen the issue.

Thanks
