### ISSUE TITLE
Products and Plans

### ISSUE THREAD

**Issue by pauloangelo** [paypal/PayPal-Python-SDK#282]
### General information

* SDK/Library version: Latest, in git
* Environment: any
* Language, language version, and OS: Python

### Issue description

Is there implementation for Products and Plans, such as described in the reference guide https://developer.paypal.com/docs/subscriptions/integrate/#2-create-a-product  ?

Thank you in advance.

Paulo Angelo

**Comment by bird-in-hat** [comment]
I wrote something like this for my own, but it's ofc a draft. And i have to catch exceptions with try/except.
Idk maybe you guys can make an improve...
Once again, it's a draft :)
https://gist.github.com/bird-in-hat/588d73ef55bc9e604a8be9bc013d5589

**Comment by prakash-gangadharan** [comment]
Hi @pauloangelo, current REST sdks still using below `Billing Plans API` which is  deprecated.
https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans

**Deprecation notice**:

-  The /v1/billing-plans endpoints are deprecated. 
- Use the /v1/billing/subscriptions endpoints instead. 
- For details, see [Subscriptions Integration](https://developer.paypal.com/docs/subscriptions/integrate/).

Currently we do not have any stipulated timeline to replace the deprecated endpoints with the newer one but it may be available in near future.

**Comment by sucithrashanu** [comment]
@pauloangelo 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.
Please Check [PayPal Community](https://www.paypal-community.com ) and  [MTS](https://paypal.com/mts)

Thanks!
