### ISSUE TITLE
exception on payout create

### ISSUE THREAD

**Issue by alonsnir** [paypal/PayPal-Python-SDK#284]
### General information

* SDK/Library version: 1.13.1
* Environment: Sandbox
* Language, language version, and OS: python 3.6, iOS

### Issue description

Payout error handling doesn't work as documented. When for example, trying to create Payout with unsufficient funds, then instead of receiving error in the resulting 'error' attribute an exception thrown.  
So instead of sample:  
```
if payout.create(sync_mode=True):
    print("payout[%s] created successfully" %
          (payout.batch_header.payout_batch_id))
else:
    print(payout.error)
```

Should be:
```
try:
    if payout.create():
        print("payout[%s] created successfully" % (payout.batch_header.payout_batch_id))
    else:
        print(payout.error)
except:
    # handle exception
```
Restful api returns in the same case the following structure with status 422
```
{
    "name": "INSUFFICIENT_FUNDS",
    "message": "Sender does not have sufficient funds. Please add funds and retry.",
    "debug_id": "c58d63e7d5527",
    "information_link": "https://developer.paypal.com/docs/api/payments.payouts-batch/#errors",
    "links": []
}
```
Could someone please suggest how to handle this? I don't see how to extract this info from the exception.

**Comment by sucithrashanu** [comment]
@alonsnir 

**Note**: sync_mode is deprecated.
So that the sample integration code will be updated  soon. 

Thanks
