### ISSUE TITLE
Check if payment was recieved.

### ISSUE THREAD

**Issue by anishanne** [paypal/PayPal-Python-SDK#286]
If I have a payment ID how do I check if a payment was received?

**Comment by sucithrashanu** [comment]
@anishanne 
Based on the state value of your transaction response we identify the payment was received or not.

The state of the payment, authorization, or order transaction. Value is:

**created**. The transaction was successfully created.
**approved**. The customer approved the transaction. The state changes from created to approved on generation of the sale_id for sale transactions, authorization_id for authorization transactions, or order_id for order transactions.
**failed**. The transaction request failed.

Thanks
