### ISSUE TITLE
Payer information is not received upon executing an agreement

### ISSUE THREAD

**Issue by dessant** [paypal/PayPal-Python-SDK#57]
Payer information is not received at any stage of the payment flow.

According to the docs, the `payer` object is returned after executing the agreement, and the `payer_info` inside it is prefilled if the `payer`'s `payment_method` is `paypal`:
https://developer.paypal.com/webapps/developer/docs/api/#execute-an-agreement
https://developer.paypal.com/webapps/developer/docs/api/#payer-object
https://developer.paypal.com/webapps/developer/docs/api/#payerinfo-object

However, none of these happen, and `payer` is not set in the execution response.

```python
def pp_agreement_create(pp_plan):
    pp_agreement = BillingAgreement({
        "name": "Billing Agreement",
        "description": "Billing Agreement",
        "start_date": "2014-08-01T07:00:00Z",
        "plan": {
            "id": pp_plan,
        },
        "payer": {
            "payment_method": "paypal"
        }
    })
    if pp_agreement.create():
        print(pp_agreement)
        for link in pp_agreement.links:
            if link.rel == "approval_url":
                print(link.href)
    else:
        print(pp_agreement.error)


def pp_agreement_execute(token):
    pp_agreement_response = BillingAgreement.execute(token)
    if pp_agreement_response.error:
        print(pp_agreement_response.error)
    else:
        print("Billing agreement executed: {}".format(pp_agreement_response.id))
        print(pp_agreement_response)
        print(pp_agreement_response.payer) # None

**Comment by avidas** [comment]
This bug is getting tracked in ( [PayPal PHP SDK Issue #155](https://github.com/paypal/PayPal-PHP-SDK/issues/155))
