### ISSUE TITLE
Google Appengine SDK problems getting started on SDK

### ISSUE THREAD

**Issue by katzlbt** [paypal/PayPal-Python-SDK#66]
From the documentation and examples I conclude that the library should work, or has worked on Appengine prior to integration of requests. I got it working in production (with lots of pain by installing urllib3 and investigating tons of outdated links and including the ssl loader). Instructions would help greatly (one requirement is a paid Appengine account for SSL support, etc.) However, I fail to get it working locally (localhost) finally with ConnectionError: ('Connection aborted.', error(13, 'Permission denied')). Who says that? Is that a local or remote message?

The first issue on GAE_SDK is the exception: "TypeError: must be _socket.socket, not socket"
Patching the sandbox on the SDK results in a permission denied error:
    "Accept": "application/json", "User-Agent": self.user_agent
  File "distlib/paypalrestsdk/api.py", line 161, in http_call
    response = requests.request(method, url, proxies=self.proxies, **kwargs)
  File "distlib/requests/api.py", line 48, in request
    return session.request(method=method, url=url, **kwargs)
  File "distlib/requests/sessions.py", line 451, in request
    resp = self.send(prep, **send_kwargs)
  File "distlib/requests/sessions.py", line 557, in send
    r = adapter.send(request, **kwargs)
  File "distlib/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))

This traces to the following exception in requests:
        except (ProtocolError, socket.error) as err:

INFO     2014-09-29 10:58:26,837 api.py:158] Request[POST]: https://api.sandbox.paypal.com/v1/oauth2/token
INFO     2014-09-29 10:58:26,849 connectionpool.py:695] Starting new HTTPS connection (1): api.sandbox.paypal.com
  File "/Users/cat/repositories/web/parts/google_appengine/google/appengine/api/remote_socket/_remote_socket.py", line 1112, in getsockopt
    raise _SystemExceptionFromAppError(e)
ProtocolError: ('Connection aborted.', error(13, 'Permission denied'))

Is this an error from the remote site or from the local system?
The connection is from a server running on localhost.

I found the following links, all of which add some insights and 
http://stackoverflow.com/questions/23093201/permission-denied-error-when-opening-socket-to-apns-on-google-appengine-developm
http://stackoverflow.com/questions/16192916/importerror-no-module-named-ssl-with-dev-appserver-py-from-google-app-engine
http://stackoverflow.com/questions/23024801/send-ios-push-notifications-from-google-app-engine-python
https://code.google.com/p/googleappengine/issues/detail?id=9246
https://github.com/stripe/stripe-python/issues/73 (payment solution stripe.com)

**Comment by avidas** [comment]
Hey @katzlbt thanks for this solution! I am going to refer to this issue in the official README as potential solution for developers trying to deploy on google appengine.

**Comment by obrizan** [comment]
@katzlbt Thanks so much for your input. Googled this discussion on another question of integrating Google App Engine and Google Cloud Storage via JSON API. Faced the same problem that 'requests' doesn't work with GCS. I've tried urfetch and it works fine.

**Comment by jmtoung** [comment]
Spent the last few hours banging my head on the wall about this issue...

@katzlbt and @obrizan - Thanks for sharing your experience in using urlfetch to get around the issue, but does anyone know another way to address the issue if swapping requests with urlfetch is NOT an option?

As others have stated, running the app in production works, but it does not work in sdk/development mode...

**Comment by katzlbt** [comment]
Use an old version of requests that works.
Can Python Requests library be used on Google App Engine?http://stackoverflow.com/questions/9604799/can-python-requests-library-be-used-on-google-app-engine

**Comment by cmin764** [comment]
https://stackoverflow.com/questions/49409783/google-app-engine-permission-denied-for-proxy-tunneling-on-development-server

**Comment by tianhuil** [comment]
With [requests toolbelt](https://github.com/requests/toolbelt), `requests` now works in both production and development:

```
from requests_toolbelt.adapters import appengine
appengine.monkeypatch()
```

For more information, [see this article](https://cloud.google.com/appengine/docs/standard/python/issue-requests).
