### ISSUE TITLE
BillingAgreement search_transactions returns empty dict for recurring payment

### ISSUE THREAD

**Issue by jutrasm** [paypal/PayPal-Python-SDK#79]
I am successfully creating and executing billing agreements.  My merchant-facilitator as well as my test-buyer are receiving Notifications in the sandbox saying that the agreement is created and subsequent Notifications that the first recurring payment has been made. 

At this point, I would like to have a daily cron job running to look at my billing agreements and see if any transactions have been made so that I can update my website's userprofile data accordingly.  In order to do this, I am calling billing_agreements.search_transactions() following your sample code provided here on GitHub. Unfortunately, this call is returning an empty dictionary as if there are no transactions for the valid billingagreement.  

I am not sure if the problem is with the search_transactions() function or if there is a problem on the sandbox end. I will note, that in my paypal dashboard I do not see any recurring "transactions" but I do see direct creditcard "Sale" transactions I have made. Also as noted, I DO receive Notifications in the sandbox accounts that the recurring payment has been made so this leads me to believe there should be transactions associated with it.

**Comment by avidas** [comment]
Hey @jutrasm which version of the sdk are you using? Are you able to get the transactions if you try the [curl request](https://developer.paypal.com/docs/api/#search-for-transactions)?

**Comment by jutrasm** [comment]
I am using version 1.6.2

I will try the curl request - not currently set up for that, but will update the outcome here once I try it.

Thanks.

**Comment by jutrasm** [comment]
***UPDATE : This is a bug in your search_transactions() function payments.py.  There is also a bug in the developer.paypal.com documentation where the curl example is incorrect.
After troubleshooting, I discovered that the "start-date" and "end-date" should actually contain underscores as follows : "start_date" and "end_date".  When I make this change, the curl works and transactions are returned to me.

**Comment by avidas** [comment]
@jutrasm would you say it got fixed with [this commit](https://github.com/paypal/PayPal-Python-SDK/commit/8bf1943f876c7be9ba131739d9ca1e805558cc94)? Updating to the latest version of the sdk should fix this for you.

**Comment by jutrasm** [comment]
@avidas Yes - Now that I've upgraded to the latest sdk, search_transactions() is returning agreement transactions to me.

Thank you!
