### ISSUE TITLE
support Automatic-billing-button's function?

### ISSUE THREAD

**Issue by nashasha1** [paypal/PayPal-Python-SDK#82]
Does PayPal-Python_SDK support the function of the automatic billing button? Means recurring payments but with different amount per month/week.

**Comment by avidas** [comment]
This is currently not a feature supported via the REST APIs. The REST subscription APIs requires that the billing plans have the amount fixed when billing agreements are formed. That amount cannot be changed later, unless you create a new billing plan with the new amount and get consent from the user. My understanding is that this is likely not the behavior you are looking for. Going for the classic recurring payments may be an option here, also follow https://developer.paypal.com/docs/ for API future enhancements.
