### ISSUE TITLE
Support for GetExpressCheckoutDetails equivalent to comply with EU VAT changes

### ISSUE THREAD

**Issue by kylemacfarlane** [paypal/PayPal-Python-SDK#83]
Since Jan 1st 2015, when selling digital services to customers in the EU the tax must be charged at the rate of their location. So to calculate the tax correctly the customer's location must be known prior to payment which is not possible with PayPal funding sources and the REST API (for credit cards you can use the BIN and billing address).

The official advice from PayPal is to use the COUNTRYCODE from GetExpressCheckoutDetails which is part of the classic API: https://ppmts.custhelp.com/app/answers/detail/a_id/1205/kw/vat

Fortunately the REST API still provides the express checkout token and so it's still possible to use GetExpressCheckoutDetails but it's a bit silly to have to call the classic API in order to comply with the law.

What are the plans to add functionality to the REST API that will make it possible to obtain a customer's COUNTRYCODE/residence_country before the final sale? Currently the only place this information is returned from the REST API is the locale field from the OpenID response and it's not reasonable to expect all customers to login with PayPal's OpenID before paying with PayPal.

**Comment by ppmtscory** [comment]
@kylemacfarlane This can already be done with PayPal payments.  After the buyer 'approves' the payment, you can do a lookup on the Payment Resource to get the address information prior to calling the Execute.  Subsequently, the [Execute](https://developer.paypal.com/webapps/developer/docs/api/#execute-an-approved-paypal-payment) call allows for a Transaction Object to be added to it so that you can modify the amount.  A couple things to keep in mind with this:

1. There will most likely be a limit on how much the amount can be increased.  As a general best practice, you'd want to show the buyer a final confirmation screen that shows the payment adjustment prior to calling the Execute.  For more information on any limits, you'd need to contact customer support.
2. For the Execute to work with a modified amount, you'll want to make sure that the 'subtotal' matches the 'subtotal' of the Create call you did prior.  You can then modify the shipping, tax, and total amounts (in the Execute call) to reflect the change.

**Comment by kylemacfarlane** [comment]
@ppmtscory 

I am not asking for a buyer's address, I am asking for the location of their bank account.

When you sign up on say paypal.com/uk/ your COUNTRYCODE gets set to GB, if you sign up on paypal.com/fr/ it gets set to FR, and so on. Since to open accounts in PayPal regions you also need a bank account in that region then in 99% of cases the COUNTRYCODE can be a proxy for the location of a buyer's bank account.

Meanwhile, a shipping address is just a shipping address.

Please reopen this ticket as it is not resolved.

**Comment by kylemacfarlane** [comment]
BTW here's a description of the various fields.

`COUNTRYCODE` from GetExpressCheckoutDetails in the classic API:
>Buyer's **country of residence** in the form of ISO standard 3166 two-character country codes.

`residence_country` from the IPN fields:
>ISO 3166 country code associated with the **country of residence**

`payer/payer_info/shipping_address` from the REST API:
>**Shipping address** of payer PayPal account.

As you can see, the shipping address returned by the REST API is not the same thing as the country of residence fields returned by other PayPal services.

**Comment by kylemacfarlane** [comment]
@ppmtscory Can you please reopen this issue as it is not resolved and the solution you provided does not help sellers comply with the new EU VAT laws.

**Comment by ppmtscory** [comment]
@kylemacfarlane As it stands currently, other than in the US, I don't believe you are allowed to have a different shipping country than your PayPal account country.  Therefore, as it relates to your issue, the shipping country from the payment resource lookup would be sufficient.  As this is a feature that may possibly change in the future, you can continue to use GetExpressCheckoutDetails for the country code if you wish.  I will file the appropriate feature request with the REST API engineers to see about having the 'residence/account country' returned in a payment resource lookup response.  As this is a feature request, I'm unable to guarantee implementation.

**Comment by kylemacfarlane** [comment]
@ppmtscory I don't think you understand what this new EU VAT law is and if not please redirect this issue to someone else. Whoever in MTS that is responsible for the VAT articles would be good.

From Jan 1st 2015, when selling digital products to customers located in the EU the VAT must be charged at the location of the customer. This even applies to US businesses selling to EU customers.

The EU requires two pieces of non-contradictory evidence to locate a customer and the only ones that really apply to sales through the web are IP address and bank account location. If the IP and bank account mismatch then you can ask for a self declaration from the customer which basically means asking them where they intend to enjoy the product aka a "shipping" address. The self declaration (shipping address) is not a suitable piece of evidence by itself.

As it stands, it's not possible to solely use the REST API to legally sell digital products to the EU.

Additionally, the documentation states that no_shipping must be set to 1 for digital sales.

**Comment by ppmtscory** [comment]
@kylemacfarlane Thank you for the extra details.  As I stated, I'm going to file the feature request for something to be returned within the REST API.  Until a decision is made on that request, you'll need to utilize GetEC if that's giving you the necessary information.
