### ISSUE TITLE
Required Scope Missing

### ISSUE THREAD

**Issue by ongspxm** [paypal/PayPal-Python-SDK#85]
When I tried creating a Payout, I couldn't really get it to work, I keep receiving the "Required Scope Missing" error. Couldn't find any answers, anyone tried using payout yet?

**Comment by avidas** [comment]
Hey is this issue happening on sandbox or live? If you are adding the payouts scope to an existing app, did you try logging into developer portal and checking that the payouts scope is checked?

**Comment by ongspxm** [comment]
It's happening on sandbox, and the payout scope option is only available for live transactions.

**Comment by jaypatel512** [comment]
At the end of the application page in [developer portal](https://developer.paypal.com/webapps/developer/applications/myapps), you should be able to see an option for Payouts similar to this:

![screen shot 2015-02-03 at 12 11 19 am](https://cloud.githubusercontent.com/assets/1309895/6015340/4fb252d6-ab39-11e4-97ab-e3385022cc15.png)

**Comment by ongspxm** [comment]
Okay, i created another app, and this time it works, i checked the settings for both apps and both of them showed all three options selected. But the previous app still doesn't work.

**Comment by ongspxm** [comment]
It works (sort of), so I am going to close the issue.
