### ISSUE TITLE
Billing Agreement start date immediately.

### ISSUE THREAD

**Issue by xxxkilldogxxx** [paypal/PayPal-Python-SDK#88]
Okay this is getting very frustrating and i'm getting fairly annoyed now as this should be simple yet its really not.

The start date for billing agreements has to be in  ISO8601 format, that is fine, I also understand you have to add around 5 mins to the UTC time you state when creating the plan in order for it to be in the future else you get a lovely error.

However if anything before UTC is considered in the past why are my billing agreements first payments 8 hours later... when I have added 5 minutes to the UTC time to make it in the "Future".

Also even if I take the UTC time add 5 minutes and then add say a timezone difference of  -0700 or -0800, the date will get accepted yet I still do not get the payment straight away?

Can you please finally clarify what the hell is going on with these dates and times as no-one really knows and its rather annoying.

Thanks
Sam Buckingham

---UPDATE---

I can bill straight away if I set the setup fee as this gets taken on profile creation, however this also means I will need to offset my start date by 1 month.

Is this the way you intended billing to happen?

-- UPDATE 2---

Everything works correctly on the live paypal site this seems to be isolated to sandbox only however this could cause confusion and should still be fix.

**Comment by avidas** [comment]
Hey @xxxkilldogxxx sorry about the confusion, could you provide some exact calls in which you ran into the live sandbox discrepancy? I agree that there should be consistency.

**Comment by xxxkilldogxxx** [comment]
Here is the exact call, which like I said failed on Sandbox but works perfectly fine on the live paypal site:

    web_profile = WebExperienceProfile.objects.get(default=True)
    subscription = SubscriptionPayment.objects.get(id=subscription_id)
    start_date = datetime.datetime.utcnow() + timedelta(minutes=5)
    formatted_date = start_date.strftime('%Y-%m-%dT%H:%M:%SZ')

    billing_agreement = BillingAgreement({
        "name": "MinecraftMarket",
        #"experience_profile_id": web_profile.profile_id, #wait for API to support experience in billing plans.
        "description": "MinecraftMarket subscription",
        "start_date": formatted_date,
        "plan": {
            "id": subscription.billing_plan_id
        },
        "payer": {
            "payment_method": "paypal"
        }
    })

**Comment by avidas** [comment]
@xxxkilldogxxx just tried it on sandbox and it created the billing agreement just fine, are you still encountering this issue?

**Comment by jaypatel512** [comment]
We have a similar issue open in PHP SDK. Just for reference adding the link here: https://github.com/paypal/PayPal-PHP-SDK/issues/180

**Comment by avidas** [comment]
Closing in favor of paypal/PayPal-PHP-SDK#180 to keep track in one place.

**Comment by viper-pranish** [comment]
I am getting the same issue. I set a start date while creating billing agreement but paypal shows start date +7 hours than what I had set. Is this a time zone issue because I have set state as CA which follows PST / PDT. 
Thank you

**Comment by mazendev** [comment]
This works for me. The customer got charged after about 5 mins from the agreement execution.

`
$st = date("Y-m-d\TH:i:s\Z",strtotime('+2 minute'));
$agreement = new Agreement();
$agreement->setName('Base Agreement')
    ->setDescription('Subscription to Pro plan for $4.99/month.')
    ->setStartDate($st);`
