### ISSUE TITLE
PAYMENT.SALE.REFUND webhook missing parameters

### ISSUE THREAD

**Issue by xxxkilldogxxx** [paypal/PayPal-Python-SDK#91]
I have been testing the webhook and have found when refunding the payment via the PayPal website the webhook notification gets sent however its missing two very important parameters that are needed in order to update my side.

This is what I receive:

{"id":"WH-83L60301F7456212Y-4RT668623J164971E","create_time":"2015-03-20T02:10:31Z","resource_type":"sale","event_type":"PAYMENT.SALE.REFUNDED","summary":"A GBP 3.99 GBP sale payment was refunded","resource":{"id":"9SL1302018633615E","create_time":"2015-03-20T02:09:33Z","state":"completed","amount":{"total":"-3.99","currency":"GBP","details":{"subtotal":"-3.99"}},"links":[{"href":"https://api.sandbox.paypal.com/v1/payments/refund/9SL1302018633615E","rel":"self","method":"GET"}]},"links":[{"href":"https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-83L60301F7456212Y-4RT668623J164971E","rel":"self","method":"GET"},{"href":"https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-83L60301F7456212Y-4RT668623J164971E/resend","rel":"resend","method":"POST"}]}

As you can see its missing "sale_id" which is needed to link the refund back to the original transaction and its also missing "parent_payment" which is useful to link back to the original payment created on my side.

I will continue to test this by executing a refund via the API on my site to see if this allows the parameters to be filled, however I would suggest these are also filled even if the refund is made via the PayPal site as it just seems logical.

--UPDATE:

I can confirm that if the refund is made via the API it includes the correct details however I think this should be either noted in the documentation but it would be better if this just worked the same across both the API and the PayPal site.

{"id":"WH-6WR36408HJ3560111-2PS004038A856171N","create_time":"2015-03-20T04:32:11Z","resource_type":"sale","event_type":"PAYMENT.SALE.REFUNDED","summary":"A GBP 14.99 GBP sale payment was refunded","resource":{"id":"30357485A8460632H","create_time":"2015-03-20T04:31:32Z","update_time":"2015-03-20T04:31:32Z","state":"completed","amount":{"total":"-14.99","currency":"GBP"},"sale_id":"393516666D741640J","parent_payment":"PAY-6M233176ST047213EKUFZ5VQ","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/refund/30357485A8460632H","rel":"self","method":"GET"},{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-6M233176ST047213EKUFZ5VQ","rel":"parent_payment","method":"GET"},{"href":"https://api.sandbox.paypal.com/v1/payments/sale/393516666D741640J","rel":"sale","method":"GET"}]},"links":[{"href":"https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-6WR36408HJ3560111-2PS004038A856171N","rel":"self","method":"GET"},{"href":"https://api.sandbox.paypal.com/v1/
 notifications/webhooks-events/WH-6WR36408HJ3560111-2PS004038A856171N/resend","rel":"resend","method":"POST"}]}

I also did try to circumvent this issue by trying to find the refund via the ID passed from the webhook and still came into issues as the api only provided me these values:

{'amount': {'currency': u'GBP', 'total': u'-3.99', 'details': {'subtotal': u'-3.99'}}, 'create_time': u'2015-03-20T02:09:33Z', 'state': u'completed', 'links': [{'href': u'https://api.sandbox.paypal.com/v1/payments/refund/9SL1302018633615E', 'method': u'GET', 'rel': u'self'}], 'id': u'9SL1302018633615E'}

However once again if the refund is made via the api it corrects the data and provides you with this:

{'update_time': u'2015-03-20T04:31:32Z', 'links': [{'href': u'https://api.sandbox.paypal.com/v1/payments/refund/30357485A8460632H', 'method': u'GET', 'rel': u'self'}, {'href': u'https://api.sandbox.paypal.com/v1/payments/payment/PAY-6M233176ST047213EKUFZ5VQ', 'method': u'GET', 'rel': u'parent_payment'}, {'href': u'https://api.sandbox.paypal.com/v1/payments/sale/393516666D741640J', 'method': u'GET', 'rel': u'sale'}], 'sale_id': u'393516666D741640J', 'state': u'completed', 'id': u'30357485A8460632H', 'amount': {'currency': u'GBP', 'total': u'-14.99'}, 'create_time': u'2015-03-20T04:31:32Z', 'parent_payment': u'PAY-6M233176ST047213EKUFZ5VQ'}

Meaning something has to be updated on regarding the PayPal site and the rest api webhooks.

**Comment by jziaja** [comment]
Thanks for reporting this behavior, @xxxkilldogxxx, and sorry for the delay in responding.  We're currently tracking this exact issue over on the [PHP SDK](https://github.com/paypal/PayPal-PHP-SDK/issues/251).  The Webhooks team is currently working on fixing this behavior as it should be producing an identical webhook notification whether a merchant uses their Dashboard or the API directly.  Once it's resolved, we'll update the thread over on the PHP SDK.

**Comment by xxxkilldogxxx** [comment]
Awesome thank you, just thought I would report this.
