### ISSUE TITLE
Billing Agreements and Web experience profiles.

### ISSUE THREAD

**Issue by xxxkilldogxxx** [paypal/PayPal-Python-SDK#92]
Thought I would just say that Web Experience profiles work for single payments however they do not work for Billing Agreements and I hope this can be fixed/enabled soon.

**Comment by jaypatel512** [comment]
Closing this issue as it is a duplicate for https://github.com/paypal/PayPal-PHP-SDK/issues/119

Please track the linked issue for any further updates. Thank you.

**Comment by xxxkilldogxxx** [comment]
Thanks
