### ISSUE TITLE
Question about state of credit card payment

### ISSUE THREAD

**Issue by minibear0523** [paypal/PayPal-Python-SDK#96]
Hello, 
I have a few questions about the state of credit card payment when I using paypalrestsdk.

When I create a payment with 'Authorize' intent and credit card, the state of payment is approved. I want to know whether the credit card charged. Because there is no way to execute a payment with credit card, so dose it mean that payment with credit card can only be charged by sale intent when create a payment?

Thanks a alot.

**Comment by jziaja** [comment]
Hi @minibear0523 , the credit card is not charged in that case until you **capture** the payment.

The `approved` state of the `payment` resource means it does not require any further approval by the buyer.  If you look at the `related_resources` included in the `payment` resource, you should see an `authorization` resource.  This resource contains the pertinent information relating to the payment authorization (how long the authorization is valid, links to capture or void the payment, and a link back to the parent `payment` resource).  A credit card payment made with `intent` set to `authorization` will only charge the credit card once the payment is captured using the `authorization` ID.  

Here's an example (from [paypalrestsdk/payments.py](https://github.com/paypal/PayPal-Python-SDK/blob/master/paypalrestsdk/payments.py#L143)):

````python
>>> authorization = Authorization.find("<AUTHORIZATION_ID>")
>>> capture = authorization.capture({ "amount": { "currency": "USD", "total": "1.00" } })
>>> authorization.void() # return True or False
````

To see a flow of this process, refer to *[Capture payments later](https://developer.paypal.com/docs/integration/direct/capture-payment/)* on PayPal Developer.

**Comment by minibear0523** [comment]
OK, I got it. Thanks a lot.
