### ISSUE TITLE
"Ship" an order

### ISSUE THREAD

**Issue by CodingSamurai** [paypal/PayPal-Python-SDK#99]
In the Paypal website you can update an order to mark it complete and to enter tracking information.  Is that functionality planned for the REST API?  It'd be a nice way to close the loop programmatically once the goods (in our case digital ones) have shipped.

**Comment by ppmtscory** [comment]
@CodingSamurai I'm not aware of any plans currently but I will file a feature request with the appropriate team.  Keep in mind that this is not a guarantee of implementation but rather a suggestion to our engineers for future updates.
